force-app/main/default/objects/EDF_CC_Global__mdt/EDF_CC_Global__mdt.object-meta.xml
<CustomObject>
    <label>EDF CC Global</label>
    <pluralLabel>EDF CC Globals</pluralLabel>
</CustomObject>

force-app/main/default/objects/EDF_NextSteps__mdt/EDF_NextSteps__mdt.object-meta.xml
<CustomObject>
    <label>EDF_NextSteps</label>
    <pluralLabel>EDF_NextSteps</pluralLabel>
</CustomObject>

force-app/main/default/objects/EDF_NextSteps__mdt/fields/NextStepsBody__c.field-meta.xml
<CustomField>
    <fullName>NextStepsBody__c</fullName>
    <label>NextStepsBody</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_NextSteps__mdt/fields/NextStepsDescription__c.field-meta.xml
<CustomField>
    <fullName>NextStepsDescription__c</fullName>
    <label>NextStepsDescription</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/EDF_NextSteps__mdt/fields/NextStepsFotter__c.field-meta.xml
<CustomField>
    <fullName>NextStepsFotter__c</fullName>
    <label>NextStepsFotter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_NextSteps__mdt/fields/NextStepsHeading__c.field-meta.xml
<CustomField>
    <fullName>NextStepsHeading__c</fullName>
    <label>NextStepsHeading</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_Shortcuts__mdt/EDF_Shortcuts__mdt.object-meta.xml
<CustomObject>
    <label>EDF Shortcuts</label>
    <pluralLabel>EDF Shortcuts</pluralLabel>
</CustomObject>

force-app/main/default/objects/EDF_Shortcuts__mdt/fields/ShortcutsBody__c.field-meta.xml
<CustomField>
    <fullName>ShortcutsBody__c</fullName>
    <label>ShortcutsBody</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_Shortcuts__mdt/fields/ShortcutsDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortcutsDescription__c</fullName>
    <label>ShortcutsDescription</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_Shortcuts__mdt/fields/ShortcutsFotter__c.field-meta.xml
<CustomField>
    <fullName>ShortcutsFotter__c</fullName>
    <label>ShortcutsFotter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EDF_Shortcuts__mdt/fields/ShortcutsLogo__c.field-meta.xml
<CustomField>
    <fullName>ShortcutsLogo__c</fullName>
    <label>ShortcutsLogo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/ItemsforEDF__mdt.object-meta.xml
<CustomObject>
    <label>ItemsforEDF</label>
    <pluralLabel>ItemsforEDFs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Button_Label__c.field-meta.xml
<CustomField>
    <fullName>Button_Label__c</fullName>
    <label>Button Label</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Button_URL__c.field-meta.xml
<CustomField>
    <fullName>Button_URL__c</fullName>
    <label>Button URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <label>Due Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Fellowship__c.field-meta.xml
<CustomField>
    <fullName>Fellowship__c</fullName>
    <label>Fellowship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
                <default>true</default>
                <label>U.S. Fellowship</label>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Header_Icon__c.field-meta.xml
<CustomField>
    <fullName>Header_Icon__c</fullName>
    <label>Header Icon</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>utility:play</fullName>
                <default>true</default>
                <label>utility:play</label>
            </value>
            <value>
                <fullName>utility:note</fullName>
            </value>
            <value>
                <fullName>utility:world</fullName>
            </value>
            <value>
                <fullName>utility:date_input</fullName>
            </value>
            <value>
                <fullName>utility:image</fullName>
            </value>
            <value>
                <fullName>utility:info</fullName>
            </value>
            <value>
                <fullName>utility:close</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/IsContactField__c.field-meta.xml
<CustomField>
    <fullName>IsContactField__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsContactField</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Item_Order__c.field-meta.xml
<CustomField>
    <fullName>Item_Order__c</fullName>
    <label>Item Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Mapping_Field__c.field-meta.xml
<CustomField>
    <fullName>Mapping_Field__c</fullName>
    <label>Mapping Field</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Section_Name__c.field-meta.xml
<CustomField>
    <fullName>Section_Name__c</fullName>
    <label>Section Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Section_Order__c.field-meta.xml
<CustomField>
    <fullName>Section_Order__c</fullName>
    <label>Section Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ItemsforEDF__mdt/fields/Tile_Body__c.field-meta.xml
<CustomField>
    <fullName>Tile_Body__c</fullName>
    <label>Tile Body</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Record_Ids__mdt/Record_Ids__mdt.object-meta.xml
<CustomObject>
    <label>Record Ids</label>
    <pluralLabel>Record Ids</pluralLabel>
</CustomObject>

force-app/main/default/objects/Record_Ids__mdt/fields/IdValue__c.field-meta.xml
<CustomField>
    <fullName>IdValue__c</fullName>
    <label>IdValue</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EDF02_CustomMetadata_Helper.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 12/29/2021
# Last Modified by......:
# Last Modified Date....:
# Description...........: Helper methods for Fetching Custom Metadata types Data.
# Test Class............: EDF02CustomMetadataHelper_Test
# Change Log:
#
############################################################################
*/
public class EDF02_CustomMetadata_Helper {

    /**
    * Description : This method return the value based on key present in the 'EDF_CC_Global__mdt' custom Metadata.
    **/
    public static String getEDFCCGlobalValue(String key) {
        // System.debug('Key:'+key);
        // System.Debug('if key not null:'+EDF_CC_Global__mdt.getAll().get(key).Value__c);
        if(key != null && EDF_CC_Global__mdt.getAll().get(key) != null)
            return EDF_CC_Global__mdt.getAll().get(key).Value__c;
        return null;
    }


    /**
    * Description : This method return the value based on key.
    **/
    public static String getStudentMessage(String key) {
        System.debug('Key:'+key);
        return null;
    }


    /**
    * Description : This method return the value based on key based to the 'Record_Ids__mdt' custom Metadata.
    **/
    public static String getRecordIdsValue(String key) {
        if(key != null && Record_Ids__mdt.getAll().get(key) != null)
            return Record_Ids__mdt.getAll().get(key).IdValue__c;
        return null;
    }


    /**
    * Description : This method return the records of 'EDF_NextSteps__mdt' custom Metadata.
    **/
    @AuraEnabled( cacheable=true )
    public static List < EDF_NextSteps__mdt > fetchEDFNextSteps() {
        List < EDF_NextSteps__mdt > fetchMeta = [ SELECT Id, MasterLabel, Active__c, NextStepsBody__c, NextStepsDescription__c, NextStepsFotter__c, NextStepsHeading__c,Order_Number__c FROM EDF_NextSteps__mdt where Active__c = true ORDER BY Order_Number__c ASC];
        return fetchMeta;
    }


    /**
    * Description : This method return the records of 'EDF_Shortcuts__mdt' custom Metadata.
    **/
    @AuraEnabled( cacheable=true )
    public static List < EDF_Shortcuts__mdt > fetchEDFShortcuts() {
        List < EDF_Shortcuts__mdt > fetchMeta = [ SELECT Id, MasterLabel, Active__c, ShortcutsBody__c, ShortcutsDescription__c, ShortcutsFotter__c, ShortcutsLogo__c,Order_Number__c FROM EDF_Shortcuts__mdt where Active__c = true ORDER BY Order_Number__c ASC];
        return fetchMeta;
    }


    /**
    * Description : This method return the records of 'ItemsforEDF__mdt' custom Metadata.
    * @param fellowshipApplyingFor: Which region fellowship data to be fetched.
    **/
    @AuraEnabled( cacheable=true )
    public static Map <String, List<ItemsforEDF__mdt> > fetchEDFItemsForFellowship(String fellowshipApplyingFor) {
        Map <String, List<ItemsforEDF__mdt>> edfItems = new Map<String, List<ItemsforEDF__mdt>>();
        List < ItemsforEDF__mdt > edfItemsList
            = [SELECT Id,
                    MasterLabel, Button_Label__c, Button_URL__c, Due_Date__c, Header_Icon__c,
                    Section_Name__c, Tile_Body__c, Section_Order__c, Item_Order__c, Mapping_Field__c,
                    IsContactField__c,
                    Hide_Due_Date__c, Due_Date_Label__c, // FB-2768
                    Due_Date_Field__c, Due_Date_Field_Offset__c // FB-2569
                FROM ItemsforEDF__mdt
                WHERE Fellowship__c =:fellowshipApplyingFor
                ORDER BY Section_Order__c, Item_Order__c ASC];
        for(ItemsforEDF__mdt item : edfItemsList){
            if(edfItems.containsKey(item.Section_Name__c)){
                edfItems.get(item.Section_Name__c).add(item);
            } else {
                edfItems.put(item.Section_Name__c, new List<ItemsforEDF__mdt>{item});
            }
        }

        // System.debug('EDF02_CustomMetadata_Helper ::: fetchEDFItemsForFellowship :::' + fellowshipApplyingFor);
        // System.debug('EDF02_CustomMetadata_Helper ::: fetchEDFItemsForFellowship :::' + edfItems);
        return edfItems;
    }


    /**
    * Description : This method return the Deliverables Tracker Tile dates to be displayed on Portal Deliverables page
    * @param fellowshipApplyingFor: Which region fellowship data to be fetched.
    **/
    @AuraEnabled( cacheable=true )
    public static List <PortalDeliverablesAndTilesDateMapping__mdt> fetchPortalDeliverablesAndTilesDateMapping(String fellowshipApplyingFor) {

        List < PortalDeliverablesAndTilesDateMapping__mdt > dateMappingsList
            = [SELECT Id,
                    MasterLabel, DeveloperName, Fellowship__c, Deliverable_Tracker_Tile__c,
                    Portal_Deliverables_Field__c,
                    Deliverable_Tracker_Tile__r.Due_Date__c,
                    Deliverable_Tracker_Tile__r.Due_Date_Field__c,
                    Deliverable_Tracker_Tile__r.Due_Date_Field_Offset__c
                FROM PortalDeliverablesAndTilesDateMapping__mdt
                WHERE Fellowship__c = :fellowshipApplyingFor];

        return dateMappingsList;
    }


    /**
    * Description : This method returns details about each section of Portal Deliverables
    * @param fellowshipApplyingFor: Which region fellowship data to be fetched.
    **/
    @AuraEnabled( cacheable=true )
    public static List <Portal_Deliverables_Section__mdt> fetchPortalDeliverablesSection(String fellowshipApplyingFor) {

        List < Portal_Deliverables_Section__mdt > sectionList
            = [SELECT Id,
                    MasterLabel, DeveloperName, Fellowship__c, Is_Visible__c,
                    Section_Field__c
                FROM Portal_Deliverables_Section__mdt
                WHERE Fellowship__c = :fellowshipApplyingFor
                ORDER BY Section_Field__c];

        return sectionList;
    }

}