force-app/main/default/objects/Climate_Corps_Engagement__c/Climate_Corps_Engagement__c.object-meta.xml
<CustomObject>
    <description>Tracks host recruitment efforts, links the host to their fellow once the match is made, and tracks all information related to that fellowship</description>
    <label>Climate Corps Engagement</label>
    <nameField>
        <label>Engagement Name (Organization, Year)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Climate Corps Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Accessible_by_public_transportation__c.field-meta.xml
<CustomField>
    <fullName>Accessible_by_public_transportation__c</fullName>
    <formula>Host_Application__r.Accessible_by_Public_Transportation__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accessible by public transportation?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Climate Corps Engagements</relationshipLabel>
    <relationshipName>Climate_Corp_Fellows</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Date_Engagement_Added_to_Portal__c.field-meta.xml
<CustomField>
    <fullName>Date_Engagement_Added_to_Portal__c</fullName>
    <label>Date Engagement Added to Portal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Fellowship_City__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_City__c</fullName>
    <formula>Host_Application__r.Fellowship_City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fellowship City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Fellowship_Metro_Area__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Metro_Area__c</fullName>
    <formula>Host_Application__r.Fellowship_Metro_Area__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fellowship Metro Area</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Fellowship_Program__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Program__c</fullName>
    <label>Fellowship Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Fellowship_State__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_State__c</fullName>
    <formula>TEXT(Host_Application__r.Fellowship_State__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fellowship State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <inlineHelpText>Lead - Cold lead, not yet responded
Contact - Contact responded, open to learning more
Interested - Contact interested, not convinced
Readied - Wants to participate
Committed - Verbally
Confirmed - Signed app
Special consideration - see notes</inlineHelpText>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Interested</fullName>
            </value>
            <value>
                <fullName>Readied</fullName>
            </value>
            <value>
                <fullName>Committed</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Confirmed Participation</fullName>
            </value>
            <value>
                <fullName>Match Conversation Complete</fullName>
            </value>
            <value>
                <fullName>Customized - Host Recruits Fellow(s)</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation In Progress</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Complete</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Accepted</fullName>
            </value>
            <value>
                <fullName>Final Deliverables Received</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Gib is recruiting</fullName>
            </value>
            <value>
                <fullName>Austin is recruiting</fullName>
            </value>
            <value>
                <fullName>Special Consideration (see notes)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Supervisor_Title__c.field-meta.xml
<CustomField>
    <fullName>Supervisor_Title__c</fullName>
    <formula>Host_Application__r.Direct_Supervisor_Title__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Direct Supervisor Title</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Workplan_Focus__c.field-meta.xml
<CustomField>
    <fullName>Workplan_Focus__c</fullName>
    <label>Workplan Focus</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Traditional EE Projects</fullName>
            </value>
            <value>
                <fullName>Strategy or Tools</fullName>
            </value>
            <value>
                <fullName>EE Strategy</fullName>
            </value>
            <value>
                <fullName>Employee Engagement</fullName>
            </value>
            <value>
                <fullName>Behavior Change</fullName>
            </value>
            <value>
                <fullName>Data Centers</fullName>
            </value>
            <value>
                <fullName>Industrial EE</fullName>
            </value>
            <value>
                <fullName>Decision Support Tools</fullName>
            </value>
            <value>
                <fullName>Funding Mechanisms</fullName>
            </value>
            <value>
                <fullName>Energy Information Systems</fullName>
            </value>
            <value>
                <fullName>Products or Services</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Workplan_for_Student_Portal__c.field-meta.xml
<CustomField>
    <fullName>Workplan_for_Student_Portal__c</fullName>
    <inlineHelpText>Shows on ConsiderMe</inlineHelpText>
    <label>Workplan for Student Portal</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Workplan_from_App__c.field-meta.xml
<CustomField>
    <fullName>Workplan_from_App__c</fullName>
    <label>Workplan Content from Application</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/Host_Application__c.object-meta.xml
<CustomObject>
    <description>Climate Corps Fellowship Program Host Applications</description>
    <label>Host Application</label>
    <nameField>
        <displayFormat>HAPP-{0}</displayFormat>
        <label>Host Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Host Application</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Host_Application__c/fields/Accessible_by_Public_Transportation__c.field-meta.xml
<CustomField>
    <fullName>Accessible_by_Public_Transportation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Accessible by Public Transportation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Host Application</relationshipLabel>
    <relationshipName>Host_Application</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Climate_Corps_Engagement__c.field-meta.xml
<CustomField>
    <fullName>Climate_Corps_Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Climate Corps Engagement</label>
    <referenceTo>Climate_Corps_Engagement__c</referenceTo>
    <relationshipLabel>Host Application</relationshipLabel>
    <relationshipName>Host_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Fellowship_City__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_City__c</fullName>
    <inlineHelpText>Shows on ConsiderMe</inlineHelpText>
    <label>Fellowship City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Fellowship_Metro_Area__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Metro_Area__c</fullName>
    <label>Fellowship Metro Area</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Fellowship_Program__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Program__c</fullName>
    <inlineHelpText>Fellowship program country</inlineHelpText>
    <label>Fellowship Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Fellowship_State__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_State__c</fullName>
    <inlineHelpText>Shows on ConsiderMe</inlineHelpText>
    <label>Fellowship State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AS</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>FM</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>GU</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MH</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Host_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Reviewed and Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potential_Matching_From_Screener__c/Potential_Matching_From_Screener__c.object-meta.xml
<CustomObject>
    <description>This join object will hold the student’s application and the engagement information. The object will hold those engagements the student is asking to be considered for, after selecting the “Consider Me” button next to the engagement on the student portal. EDF staff will also use this object as a result of the matching process initiated by an EDF staff person from the student application or engagement record.</description>
    <label>Consider Me- Fellow Portal</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>PE Match #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consider Me- Fellow Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Potential_Matching_From_Screener__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engagement</label>
    <referenceTo>Climate_Corps_Engagement__c</referenceTo>
    <relationshipName>Potential_Matching_From_Screeners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EngagementComparatorWrapper.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 3/28/2022
# Last Modified by......:
# Last Modified Date....:
# Description...........: This Class contains EngagementList Wrapper.
# Test Class............: EngagementListController_Test
# Change Log:
#
############################################################################
*/
global class EngagementComparatorWrapper implements Comparable {
	@AuraEnabled
    public Id eId { get; set; }
    @AuraEnabled
    public String Workplan_Focus { get; set; }
    @AuraEnabled
    public String Supervisor_Title { get; set; }
    @AuraEnabled
    public String Fellowship_State { get; set; }
    @AuraEnabled
    public String Engagement_Program { get; set; }
    @AuraEnabled
    public String Fellowship_Metro_Area { get; set; }
    @AuraEnabled
    public String Fellowship_City { get; set; }
    @AuraEnabled
    public Date Date_Engagement_Added_to_Portal { get; set; }
    @AuraEnabled
    public Account acc { get; set; }
    @AuraEnabled
    public Id accId { get; set; }
    @AuraEnabled
    public String AccountName { get; set; }
    @AuraEnabled
    public String Stage { get; set; }
    @AuraEnabled
    public Boolean Accessible_by_public_transportation { get; set; }
    @AuraEnabled
    public String Available_NotAvailable { get; set; }
    @AuraEnabled
    public String Workplan_from_App { get; set; }
    @AuraEnabled
    public String Engagement_Type { get; set; }
    @AuraEnabled
    public Boolean considerMe { get; set; }
    @AuraEnabled
    public Climate_Corps_Engagement__c engagement { get; set; }
    @AuraEnabled
    public String Name { get; set; }
    @AuraEnabled
    public String Past_CC_Years { get; set; }
    @AuraEnabled
    public String Workplan_Environment{ get; set; }
    @AuraEnabled
    public String Supervisor2{ get; set; }
    @AuraEnabled
    public String Matching_Notes_from_EDF{ get; set; }
    @AuraEnabled
    public String High_Level_Sponsor2{ get; set; }
    @AuraEnabled
    public String High_Level_Sponsor_Title{ get; set; }
    @AuraEnabled
    public String howConsidered { get; set; }
    @AuraEnabled
    public Boolean potentialMatch { get; set; }
    @AuraEnabled
    public String Industry { get; set; } // 16-Jan-2015
    @AuraEnabled
    public String Project_Type { get; set; } // 16-Jan-2015
    @AuraEnabled
    public String sortBy = 'Date_Engagement_Added_to_Portal__c';
    @AuraEnabled
    public String sortDir = 'desc';

    // public String reason { get; set; } // 8-Dec-2015 - Sakshi
    @AuraEnabled
    public boolean competitiveHost { get; set; } // 9-Dec-2015 - Sakshi
    @AuraEnabled
    public Potential_Matching_From_Screener__c considerMeMatch { get; set; } // 14-Dec-2015 - Harpreet
    @AuraEnabled
    public String Fellowship_Location_Preference {get; set;} // 26-OCT-2020 - SaiTeja
    @AuraEnabled
    public boolean prioritizeHost { get; set; } // 7/1/21 - Harpreet

    @AuraEnabled
    public String starColor { get; set; } // FB-2133 Harpreet

    public EngagementComparatorWrapper(Climate_Corps_Engagement__c engg, String sortBy, String sortDir) {
        setEngagementData(engg);
        if (sortBy != null  &&  sortBy != '') this.sortBy = sortBy;
        if (sortDir != null  &&  sortDir != '') this.sortDir = sortDir;
    }

    public EngagementComparatorWrapper(Potential_Matching_From_Screener__c pms, Boolean considerMe, Boolean fromEDF, String sortBy, String sortDir) {
        setEngagementDataFromPMS(pms, considerMe, fromEDF);
        if (sortBy != null  &&  sortBy != '') this.sortBy = sortBy;
        if (sortDir != null  &&  sortDir != '') this.sortDir = sortDir;
    }

    private void setEngagementData(Climate_Corps_Engagement__c eng) {
        eId = eng.Id;
        Workplan_Focus = eng.Workplan_Focus__c;
        Supervisor_Title = eng.Supervisor_Title__c;
        Fellowship_State = eng.Fellowship_State__c;
        Engagement_Program = eng.Fellowship_Program__c;
        //j/Fellowship_Metro_Area = eng.Fellowship_Metro_Area__c;
        Fellowship_City = eng.Fellowship_City__c;
        Date_Engagement_Added_to_Portal = eng.Date_Engagement_Added_to_Portal__c;
        // public Account acc { get; set; }
        accId = eng.Account__c;
        AccountName = eng.Account__r.Name;
        Stage = eng.Stage__c;
        Accessible_by_public_transportation = eng.Accessible_by_public_transportation__c;
        Workplan_from_App = eng.Workplan_for_Student_Portal__c;
        // Workplan_from_App = eng.Workplan_from_App__c;
        starColor = eng.Star__c; // FB-2133 Harpreet

        Industry = eng.Industry_Classification__c; // 16-Jan-2015
        // Project_Type = eng.Work_Scope_Bucket__c; // 16-Jan-2015
        Project_Type = eng.Project_Category__c; // For using Project Category of Host Application
        Fellowship_Location_Preference = eng.Fellowship_Location_Preference__c; //26-OCT-2020.
        Available_NotAvailable = 'Not Available';
        if (eng.Stage__c == 'Confirmed Participation'
                ||  eng.Stage__c == 'Match Conversation Complete'
                ||  eng.Stage__c == 'Onboarding Conversation Not Accepted') {
            Available_NotAvailable = 'Available';
        }
        else if(eng.Stage__c == 'Offer sent' || eng.Stage__c == 'Onboarding Conversation in Progress' || eng.Stage__c == 'Onboarding Conversation Complete'){
            Available_NotAvailable = 'Unavailable: Offer Pending';
        }

        considerMe = false;
        if (eng.Potential_Matching_From_Screeners__r != null  &&  eng.Potential_Matching_From_Screeners__r.size() > 0  &&  Available_NotAvailable == 'Available') {
            considerMe = true;
        }

        Name = eng.Name != null ? eng.Name : '';
        //j/Past_CC_Years = eng.Past_CC_Years__c != null ? eng.Past_CC_Years__c : '';
        Supervisor2 = eng.Supervisor2__c != null ? eng.Supervisor2__c : '';
        Matching_Notes_from_EDF = eng.Matching_Notes_from_EDF__c != null ? eng.Matching_Notes_from_EDF__c : '';
        //j/High_Level_Sponsor_Title = eng.High_Level_Sponsor_Title__c != null ? eng.High_Level_Sponsor_Title__c : '';
        howConsidered = '';
        potentialMatch = false;
        //Code changes by Sakshi on 9-Dec-2015 start
        competitiveHost = false;
        if ((eng.Competitive_Host_Location__c != null  &&  eng.Competitive_Host_Location__c == TRUE) || (eng.Competitive_Host_based_on_ConsiderMe__c == TRUE)) {
            competitiveHost = true;
        }
        //Code changes by Sakshi on 9-Dec-2015 end

        /**
         * Show blue icon next to Name if Engagement is prioritized
         * Added by Harpreet (OSI) on 7/1/21
         */
        prioritizeHost = false;
        if (eng.Prioritize_for_Consider_Mes__c != null  &&  eng.Prioritize_for_Consider_Mes__c == TRUE) {
            prioritizeHost = true;
        }

        // reason = ''; // 8-Dec-2015 - Sakshi
        considerMeMatch = new Potential_Matching_From_Screener__c();
        considerMeMatch.Engagement__c = eng.Id;
        if (eng.Potential_Matching_From_Screeners__r != null  &&  eng.Potential_Matching_From_Screeners__r.size() > 0) {
            Boolean[] matchType = new Boolean[] { false, false };
            for (Potential_Matching_From_Screener__c match : eng.Potential_Matching_From_Screeners__r) {
                if (match.How_Considered__c == 'EDF') {
                    matchType[0] = true;
                }
                else {
                    matchType[1] = true;
                }
                howConsidered = match.How_Considered__c;
                if (matchType[0] == true  &&  matchType[1] == true) {
                    howConsidered = 'Both';
                    break;
                }
                // 8-Dec-2015 - Sakshi
                if(String.isNotBlank(match.Why__c)){
                    // reason = match.Why__c;
                    considerMeMatch.Why__c = match.Why__c; // Harpreet - 14-Dec-2015
                }
                considerMeMatch.Bookmark__c = match.Bookmark__c;
                considerMeMatch.Rank__c = match.Rank__c;
                considerMeMatch.Status__c = match.Status__c; // FB-1917 Harpreet
                considerMeMatch.Id = match.Id;
                System.debug('considerMeMatch :::::' + considerMeMatch + '\r\n match ::::' + match);
            }
            potentialMatch = true;
        }
        engagement = eng;
    }

    private void setEngagementDataFromPMS(Potential_Matching_From_Screener__c pms, Boolean considerMe, Boolean fromEDF) {
        eId = pms.Engagement__c;
        Workplan_Focus = pms.Engagement__r.Workplan_Focus__c;
        Supervisor_Title = pms.Engagement__r.Supervisor_Title__c;
        Fellowship_State = pms.Engagement__r.Fellowship_State__c;
/*        Fellowship_Metro_Area = pms.Engagement__r.Host_application__r.Fellowship_Metro_Area__c;
*/      Fellowship_City = pms.Engagement__r.Fellowship_City__c;
        Date_Engagement_Added_to_Portal = pms.Engagement__r.Date_Engagement_Added_to_Portal__c;
        accId = pms.Engagement__r.Account__c;
        AccountName = pms.Engagement__r.Account__r.Name;
        Stage = pms.Engagement__r.Stage__c;
        Accessible_by_public_transportation = pms.Engagement__r.Accessible_by_public_transportation__c;
        Workplan_from_App = pms.Engagement__r.Workplan_from_App__c;
        name = pms.Engagement__r.Name;

        // Project_Type = pms.Engagement__r.Work_Scope_Bucket__c; // 16-Jan-2015
        Project_Type = pms.Engagement__r.Project_Category__c; // For using Project Category of Host Application
        Fellowship_Location_Preference = pms.Engagement__r.Fellowship_Location_Preference__c; //26-OCT-2020

        Available_NotAvailable = 'Not Available';
        Industry = pms.Engagement__r.Industry_Classification__c; // 16-Jan-2015
        if (pms.Engagement__r.Stage__c == 'Confirmed Participation'
                ||  pms.Engagement__r.Stage__c == 'Match Conversation Complete'
                ||  pms.Engagement__r.Stage__c == 'Onboarding Conversation Not Accepted') {
            Available_NotAvailable = 'Available';
        }

        this.considerMe = considerMe;

        if (considerMe == true  &&  fromEDF  == true)
            howConsidered = 'Both';
        else if (considerMe == true  &&  fromEDF  == false)
            howConsidered = 'Consider Me';
        else if (considerMe == false  &&  fromEDF  == true)
            howConsidered = 'Potential Match from EDF';
        else if (considerMe == false  &&  fromEDF  == false)
            howConsidered = '';

        if (howConsidered != '') potentialMatch = true; else potentialMatch = false;

        Name = pms.Engagement__r.Name != null ? pms.Engagement__r.Name : '';
        //j/Past_CC_Years = pms.Engagement__r.Past_CC_Years__c != null ? pms.Engagement__r.Past_CC_Years__c : '';
        Supervisor2 = pms.Engagement__r.Supervisor2__c != null ? pms.Engagement__r.Supervisor2__c : '';
        Matching_Notes_from_EDF = pms.Engagement__r.Matching_Notes_from_EDF__c != null ? pms.Engagement__r.Matching_Notes_from_EDF__c : '';
        //j/High_Level_Sponsor_Title = pms.Engagement__r.High_Level_Sponsor_Title__c != null ? pms.Engagement__r.High_Level_Sponsor_Title__c : '';
        starColor = pms.Engagement__r.Star__c; // FB-2133 Harpreet
    }


    global Integer compareTo(Object compareTo) {
        EngagementComparatorWrapper compareToEng = (EngagementComparatorWrapper)compareTo;

        String[] vals = getValue(this, compareToEng, sortBy);

        String currValue = vals[0];
        String compareToValue = vals[1];

        if (sortDir.toLowerCase() == 'asc') {
            if (currValue > compareToValue) {
                return 1;
            }
            else if (currValue < compareToValue) {
                return -1;
            }
        }
        else if (sortDir.toLowerCase() == 'desc') {
            if (currValue < compareToValue) {
                return 1;
            }
            else if (currValue > compareToValue) {
                return -1;
            }
        }
        return 0;
    }

    private String[] getValue(EngagementComparatorWrapper engg, EngagementComparatorWrapper compareToEngg, String sortBy) {
        System.debug('::::: sortBy in GetValue :::::' + sortBy);
        List<String> retVal = new List<String>();

        if (sortBy == 'Available_NotAvailable'  ||  sortBy == 'AccountName') {
            if (sortBy == 'AccountName') {
                retVal.add(engg.AccountName);
                retVal.add(compareToEngg.AccountName);
            }
            else if (sortBy == 'Available_NotAvailable') {
                retVal.add(engg.Available_NotAvailable);
                retVal.add(compareToEngg.Available_NotAvailable);
            }
        }
        else {
            retVal.add(String.valueOf(engg.engagement.get(sortBy)));
            retVal.add(String.valueOf(compareToEngg.engagement.get(sortBy)));
        }

        /*
        if (sortBy == 'AccountName') {
            retVal.add(engg.AccountName);
            retVal.add(compareToEngg.AccountName);
        }
        else if (sortBy == 'Engagement_Type') {
            retVal.add(engg.Engagement_Type);
            retVal.add(compareToEngg.Engagement_Type);
        }
        else if (sortBy == 'Supervisor_Title') {
            retVal.add(engg.Supervisor_Title);
            retVal.add(compareToEngg.Supervisor_Title);
        }
        else if (sortBy == 'Accessible_by_public_transportation') {
            retVal.add(String.valueOf(engg.Accessible_by_public_transportation));
            retVal.add(String.valueOf(compareToEngg.Accessible_by_public_transportation));
        }
        else if (sortBy == 'Fellowship_Metro_Area') {
            retVal.add(engg.Fellowship_Metro_Area);
            retVal.add(compareToEngg.Fellowship_Metro_Area);
        }
        else if (sortBy == 'Fellowship_City') {
            retVal.add(engg.Fellowship_City);
            retVal.add(compareToEngg.Fellowship_City);
        }
        else if (sortBy == 'Fellowship_State') {
            retVal.add(engg.Fellowship_State);
            retVal.add(compareToEngg.Fellowship_State);
        }
        else if (sortBy == 'Workplan_Focus') {
            retVal.add(engg.Workplan_Focus);
            retVal.add(compareToEngg.Workplan_Focus);
        }
        else if (sortBy == 'Date_Engagement_Added_to_Portal') {
            System.debug('::::: Inside Date Sorting :::::');
            System.debug('::::: engg.Date_Engagement_Added_to_Portal :::::' + engg.Date_Engagement_Added_to_Portal);
            System.debug('::::: compareToEngg.Date_Engagement_Added_to_Portal :::::' + compareToEngg.Date_Engagement_Added_to_Portal);
            System.debug('::::: engg.Date_Engagement_Added_to_Portal :::::' + String.valueOf(engg.Date_Engagement_Added_to_Portal));
            System.debug('::::: compareToEngg.Date_Engagement_Added_to_Portal :::::' + String.valueOf(compareToEngg.Date_Engagement_Added_to_Portal));
            retVal.add(String.valueOf(engg.Date_Engagement_Added_to_Portal));
            retVal.add(String.valueOf(compareToEngg.Date_Engagement_Added_to_Portal));
        }
        else if (sortBy == 'Available_NotAvailable') {
            retVal.add(engg.Available_NotAvailable);
            retVal.add(compareToEngg.Available_NotAvailable);
        }
        */
        System.debug('::::: retVal :::::' + retVal);
        return retVal;
    }
}