force-app/main/default/objects/Climate_Corps_Engagement__c/Climate_Corps_Engagement__c.object-meta.xml
<CustomObject>
    <description>Tracks host recruitment efforts, links the host to their fellow once the match is made, and tracks all information related to that fellowship</description>
    <label>Climate Corps Engagement</label>
    <nameField>
        <label>Engagement Name (Organization, Year)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Climate Corps Engagements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Complete_Post_Training_Items__c.field-meta.xml
<CustomField>
    <fullName>Complete_Post_Training_Items__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Complete Post Training Items</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/CompleteTrainingPreWork__c.field-meta.xml
<CustomField>
    <fullName>CompleteTrainingPreWork__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Please complete the training pre-work as described in this document prior to the start of the Fellow Training.</inlineHelpText>
    <label>Complete Training Pre-Work</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <formula>Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recruitment Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Engagement_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engagement_Notes__c</fullName>
    <label>Key Stakeholder Notes from Final Report</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Fellow_Application__c.field-meta.xml
<CustomField>
    <fullName>Fellow_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fellow Application</label>
    <referenceTo>Fellow_Application__c</referenceTo>
    <relationshipLabel>Climate Corps Engagements</relationshipLabel>
    <relationshipName>Climate_Corps_Engagements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Kilowatt_Signup__c.field-meta.xml
<CustomField>
    <fullName>Kilowatt_Signup__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the fellow signed up for the Kilowatt</inlineHelpText>
    <label>Kilowatt Signup</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Media_Profile__c.field-meta.xml
<CustomField>
    <fullName>Media_Profile__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Media Profile</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Orientation_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Orientation_Webinar__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Fellow confirmed if they watched the Orientation Webinar</inlineHelpText>
    <label>Orientation Webinar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Project_Database_Submitted__c.field-meta.xml
<CustomField>
    <fullName>Project_Database_Submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>checkbox is checked when the Final Deliverables are Submitted</description>
    <inlineHelpText>checkbox is checked when the Final Deliverables are Submitted</inlineHelpText>
    <label>Project Database Submitted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Registered_for_Training__c.field-meta.xml
<CustomField>
    <fullName>Registered_for_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Fellow confirmed in the portal that they registered for training.</inlineHelpText>
    <label>Registered for Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Requested_Mentor__c.field-meta.xml
<CustomField>
    <fullName>Requested_Mentor__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Fellow indicated they submitted a form to request a mentor</inlineHelpText>
    <label>Requested Mentor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Reviewed_HR_Webinar__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_HR_Webinar__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the fellow watched the HR webinar (EDF paid fellows only).</inlineHelpText>
    <label>Reviewed HR Webinar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Reviewed_Work_Authorization__c.field-meta.xml
<CustomField>
    <fullName>Reviewed_Work_Authorization__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the fellow reviewed the work authorization policy (international students only).</inlineHelpText>
    <label>Reviewed Work Authorization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Submit_Final_Deliverables__c.field-meta.xml
<CustomField>
    <fullName>Submit_Final_Deliverables__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Final Deliverables</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Submit_Start_End_dates__c.field-meta.xml
<CustomField>
    <fullName>Submit_Start_End_dates__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Start &amp; End dates</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Submit_Workplan__c.field-meta.xml
<CustomField>
    <fullName>Submit_Workplan__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submit Workplan</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Training_Info_Survey__c.field-meta.xml
<CustomField>
    <fullName>Training_Info_Survey__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Training Info &amp; Survey</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Climate_Corps_Engagement__c/fields/Twitter_Handle__c.field-meta.xml
<CustomField>
    <fullName>Twitter_Handle__c</fullName>
    <formula>Fellow_Name__r.Twitter_Handle__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Twitter Handle</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Bio__c.field-meta.xml
<CustomField>
    <fullName>Bio__c</fullName>
    <label>Bio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold the emails related to a Contact.</description>
    <label>Contact Email</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Current&quot;</defaultValue>
    <description>Status of email on record.</description>
    <inlineHelpText>Indicates if email is current or former.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
                <isActive>false</isActive>
                <label>Former</label>
            </value>
            <value>
                <fullName>Former_Archived</fullName>
                <isActive>false</isActive>
                <label>Former_Archived</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ContentVersion/fields/Deleted_By_Fellow__c.field-meta.xml
<CustomField>
    <fullName>Deleted_By_Fellow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deleted By Fellow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordId__c/RecordId__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Record Ids</label>
</CustomObject>

force-app/main/default/objects/RecordId__c/fields/IdValue__c.field-meta.xml
<CustomField>
    <fullName>IdValue__c</fullName>
    <label>IdValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EngagementController_Test.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 1/31/2022
# Last Modified by......:
# Last Modified Date....:
# Description...........: Test class for Engagement_Controller
# Change Log:
#
#
############################################################################
*/


@isTest
public class EngagementController_Test {

    // public static String email = 'someone@abc.bix';
    // public static String fellowshipYear = '' + System.today().year();

    public static Constants constt = Constants.getAllConstants();
    public static String FELLOWSHIP_REGION = constt.FELLOWSHIP_REGION_PICKLIST_US;
    public static Map<String, String> staticTestData = new Map<String, String> {
                'email' => 'someone@abc.bix',
                'firstName' => 'Harpreet',
                'lastName' => 'Singh',
                'fellowshipYear' => ('' + System.today().year())
            };

    @testsetup
    public static void createTestData() {
        createCustomSettingData();
        createBusinessData();
    }
    static testMethod void testCreateContact() {

        Contact c = TestFactory.retrieveContact(null, null, null);

        // Climate_Corps_Engagement__c ce = TestFactory.retrieveEngagement(null, null, null);
        Climate_Corps_Engagement__c ceRecord = TestFactory.retrieveEngagement(
            null,
            new List<String> {
                'Fellow_Application__r.Applicant__c',
                'Fellow_Application__r.Applicant__r.Bio__c',
                'Fellow_Application__r.Applicant__r.Twitter_Handle__c',
                'Fellow_Application__r.Applicant__r.LinkedIn_Profile__c'
            },
            null);

        ContentVersion cv = TestFactory.retrieveContentVersion(null, null, null);
        Id conDocId = cv.ContentDocumentId;
        ContentDocumentLink cdl = TestFactory.retrieveContentDocumentLink(new Map<String, Object> {
                'LinkedEntityId' => '\'' + ceRecord.Id + '\'',
                'ContentDocument.LatestPublishedVersion.Deleted_By_Fellow__c' => false
            }, null, null);

        User u = TestFactory.retrieveUser(new Map<String, Object> {
                'Email' => '\'' + staticTestData.get('email') + '\''
            }, null, null);
        System.debug('User ::' + u);

        System.runAs(u){
            Test.startTest();
            Engagement_Controller.getFellowEngagementEDF();
            EDF02_CustomMetadata_Helper.fetchEDFItemsForFellowship(FELLOWSHIP_REGION);
            Engagement_Controller.getEngagementAttachments(ceRecord);
            Engagement_Controller.validateCCEngagementForSave();

            //Convert the id into string since the methods expecting id as string
            String ccId = Id.valueOf(ceRecord.Id); // climate corps Id
            // String ccIdafterQuery  = Id.valueOf(ceRecord.id);
            String conId = Id.valueOf(c.Id); // Contact Id
            String contentDocumnetLinkId = Id.valueOf(cdl.Id); // contentDocumnetLinkId
            String contentVersionId = Id.valueOf(cv.id); //contentVersionId
            Engagement_Controller.updateFellowEngagement('Orientation_Webinar__c', false, ccId, conId);
			Engagement_Controller.updateFellowEngagement('Kilowatt_Signup__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Reviewed_Work_Authorization__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Reviewed_HR_Webinar__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Registered_for_Training__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('CompleteTrainingPreWork__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Requested_Mentor__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Training_Info_Survey__c', false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Submit_Start_End_dates__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Submit_Workplan__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Submit_Workplan__c',false, ccId, conId); // To test value being set to False
            Engagement_Controller.updateFellowEngagement('Media_Profile__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Submit_Final_Deliverables__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('Complete_Post_Training_Items__c',false, ccId, conId);
            Engagement_Controller.updateFellowEngagement('CC_Alumni_Group_Member', true, ccId, conId);
            Engagement_Controller.updateFellowEngagement('CC_Alumni_Group_Member', true, ccId, conId); // To test value being set to False
            Engagement_Controller.updateFellowEngagement('On_EDF_Connect_Platform', true, ccId, conId);

           	Engagement_Controller.updateEngagement(ceRecord,'Solar and/or Wind','Absolute goals or targets','ced','def','someone@abc.bix','efg','fgh','ghi', FELLOWSHIP_REGION);
            Engagement_Controller.fetchFiles(ccId);
            Engagement_Controller.renameAttachments(contentVersionId, constt.CC_ENGAGEMENT_WORKPLAN_FILE_TITLE_PREFIX, ccId, FELLOWSHIP_REGION);
            Engagement_Controller.deleteDocument(contentVersionId,conDocId, null, null, null);
            Engagement_Controller.deleteDocument(null,conDocId, null, null, null);
            Engagement_Controller.updateFieldValue(ccId, 'Project_Database_Submitted__c', 'true', 'Climate_Corps_Engagement__c', true);
            Engagement_Controller.updateFieldValue(ccId, 'Engagement_Notes__c', '123', 'Climate_Corps_Engagement__c', false);

            Test.stopTest();

            AttachmentResource ar;
            ar = Engagement_Controller.projectDataBaseAttachment;
            ar = Engagement_Controller.remainingDeliverablesAttachment;
            ar = Engagement_Controller.onsitePhotoAttachment3;
            ar = Engagement_Controller.onsitePhotoAttachment2;
            ar = Engagement_Controller.onsitePhotoAttachment;
            ar = Engagement_Controller.workPlanAttachment;
            ar = Engagement_Controller.photoAttachment;

            Boolean flag = Engagement_Controller.flag;
            Fellow_Application__c fa = Engagement_Controller.fellowApp;
            String deadline = Engagement_Controller.deadlineForPreFellowship;

            System.assertEquals(Engagement_Controller.flattenCheckboxData(new List<String> { 'Text1', 'Text2', 'Text3'}), 'Text1;Text2;Text3');

            Engagement_Controller.fetchDeliverableDates('U.S. Fellowship', ceRecord.id);
        }

        TestFactory.updateContentVersion(Id.valueOf(cv.id),
            new Map<String, Object> {
                'Title' => constt.CC_ENGAGEMENT_WORKPLAN_FILE_TITLE_PREFIX + '_' + staticTestData.get('fellowshipYear') + '_' + staticTestData.get('firstName') + '_' + staticTestData.get('lastName') + '_' +System.today().year()+'_'+System.today().month()+'_'+System.today().day()+'_'+System.now().hour()+'_'+System.now().minute()+'_'+System.now().second()
            }, true);

    }


    static testMethod void testSavePersonalEmailAddress() {

        Contact c = TestFactory.retrieveContact(null, null, null);

        // Climate_Corps_Engagement__c ce = TestFactory.retrieveEngagement(null, null, null);
        Climate_Corps_Engagement__c ceRecord = TestFactory.retrieveEngagement(
            null,
            new List<String> {
                'Fellow_Application__r.Applicant__c',
                'Fellow_Application__r.Applicant__r.Bio__c',
                'Fellow_Application__r.Applicant__r.Twitter_Handle__c',
                'Fellow_Application__r.Applicant__r.LinkedIn_Profile__c'
            },
            null);

        User u = TestFactory.retrieveUser(new Map<String, Object> {
                'Email' => '\'' + staticTestData.get('email') + '\''
            }, null, null);
        System.debug('User ::' + u);

        System.runAs(u){
            Test.startTest();
            Engagement_Controller.getFellowEngagementEDF();

            // Test validateCCEngagementForSave
            Climate_Corps_Engagement__c ccEngagement = Engagement_Controller.ccEngagement;
            EDF02_CustomMetadata_Helper.fetchEDFItemsForFellowship('U.S. Fellowship');
            ccEngagement.Fellow_Application__r.Applicant__r.Bio__c = '';
            for (Integer ctr = 0; ctr < 150; ctr++) {
                ccEngagement.Fellow_Application__r.Applicant__r.Bio__c += 'Text ';
            }
            Engagement_Controller.validateCCEngagementForSave();
            ccEngagement.Fellow_Application__r.Applicant__r.Bio__c = 'Bio';

            // Test savePersonalEmailAddress
           	Engagement_Controller.updateEngagement(ceRecord,'Solar and/or Wind','Absolute goals or targets','ced','def','someone.1@abc.bix','efg','fgh','ghi', FELLOWSHIP_REGION);

            Test.stopTest();
        }
    }


    static testMethod void testOnsitePhotoAttachment() {

        Contact c = TestFactory.retrieveContact(null, null, null);

        // Climate_Corps_Engagement__c ce = TestFactory.retrieveEngagement(null, null, null);
        Climate_Corps_Engagement__c ceRecord = TestFactory.retrieveEngagement(
            null,
            new List<String> {
                'Fellow_Application__r.Applicant__c',
                'Fellow_Application__r.Applicant__r.Bio__c',
                'Fellow_Application__r.Applicant__r.Twitter_Handle__c',
                'Fellow_Application__r.Applicant__r.LinkedIn_Profile__c'
            },
            null);

        ContentVersion cv = TestFactory.retrieveContentVersion(new Map<String, Object> {
                'Title' => '\'' + constt.CC_ENGAGEMENT_ONSITE_PHOTO_FILE_TITLE_PREFIX + '%\''
            }, null, null);
        Id conDocId = cv.ContentDocumentId;
        ContentDocumentLink cdl = TestFactory.retrieveContentDocumentLink(new Map<String, Object> {
                'LinkedEntityId' => '\'' + ceRecord.Id + '\'',
                'ContentDocument.LatestPublishedVersion.Deleted_By_Fellow__c' => false
            }, null, null);

        User u = TestFactory.retrieveUser(new Map<String, Object> {
                'Email' => '\'' + staticTestData.get('email') + '\''
            }, null, null);
        System.debug('User ::' + u);

        System.runAs(u){
            Test.startTest();
            Engagement_Controller.getFellowEngagementEDF();

            // Test validateCCEngagementForSave
            Engagement_Controller.renameAttachments(cv.Id, constt.CC_ENGAGEMENT_ONSITE_PHOTO_FILE_TITLE_PREFIX, ceRecord.Id, FELLOWSHIP_REGION);

            Test.stopTest();
        }
    }

    public static void createCustomSettingData() {
        List<RecordId__c> recordIdCustomSetting = new List<RecordId__c>();
        if(RecordId__c.getAll().get('DefaultOwnerId') == NULL){
            recordIdCustomSetting.add(new RecordId__c(name = 'DefaultOwnerId',IdValue__c = string.valueOf(UserInfo.getUserId())));
        }
        if(recordIdCustomSetting.size()>0){
            insert recordIdCustomSetting;
        }

        List<EDFCCGlobal__c> EDFCCglobalCustomSetting = new List<EDFCCGlobal__c>();
        if(EDFCCGlobal__c.getAll().get('CurrentFellowshipYear') == NULL){
            EDFCCglobalCustomSetting.add(new EDFCCGlobal__c(name = 'CurrentFellowshipYear', Value__c = staticTestData.get('fellowshipYear') ));
        }
        if(EDFCCglobalCustomSetting.size()>0){
            insert EDFCCglobalCustomSetting;
        }
    }

    public static void createBusinessData() {
        Account a = TestFactory.createAccount('Test Account',
            new Map<String, Object> {
                'OwnerId' => CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')
            },
            true);
        Contact c = TestFactory.createContact(a.Id, 'TestLN',
            new Map<String, Object> {
                'FirstName' => 'TestFN',
                'Email' => 'someone@abc.bix',
                'Phone' => '9876543210',
                'MailingStreet' => 'Street',
                'MailingCity' => 'New Delhi',
                'MailingState' => 'Delhi',
                'MailingCountry' => 'India',
                'MailingPostalCode' => '110060',
                'Twitter_Handle__c' => '@twitter',
                'LinkedIn_Profile__c' => 'LinkedIn',
                'Bio__c' => 'test'
            },
            true );
        Contact_Email__c conEmail = TestFactory.createContactEmail(c.id,
            new Map<String, Object> {
                'Type__c' => 'personaal',
                'Primary__c' => false
            },
            true);

        Fellow_Application__c fa = TestFactory.createFellowApplication(c.Id,
            new Map<String, Object> {
                'Status__c' => 'Engagement Confirmed',
                'CC_Year__c' => staticTestData.get('fellowshipYear')
            },
            true);
        Climate_Corps_Engagement__c ce = TestFactory.createEngagement('OSI DEV, 2022',
            new Map<String, Object> {
                'Fellow_Application__c' => fa.id,
                'CC_Year__c' => staticTestData.get('fellowshipYear')
            },
            true);
        Climate_Corps_Engagement__c ceRecord = TestFactory.retrieveEngagement(null, null, null);



        ContentVersion cv = TestFactory.createContentVersion(
            new Map<String, Object> {
                'Title' => constt.CC_ENGAGEMENT_WORKPLAN_FILE_TITLE_PREFIX + '_' + staticTestData.get('fellowshipYear') + '_' + staticTestData.get('firstName') + '_' + staticTestData.get('lastName') + '_'
            }, true);
        ContentDocumentLink cdl = TestFactory.createContentDocumentLink(cv, null, ce.Id, null, true);


        // Second file for testing Deletion scenario
        ContentVersion cv1 = TestFactory.createContentVersion(
            new Map<String, Object> {
                'Title' => constt.CC_ENGAGEMENT_WORKPLAN_FILE_TITLE_PREFIX + '_' + staticTestData.get('fellowshipYear') + '_' + staticTestData.get('firstName') + '_' + staticTestData.get('lastName') + '_'
            }, true);
        ContentDocumentLink cdl1 = TestFactory.createContentDocumentLink(cv1, null, ce.Id, null, true);


        // PhotoOnsite test scenario
        List<ContentVersion> onsitePhotosCV = TestFactory.createMultipleContentVersions(
            new Map<String, Object> {
                'Title' => constt.CC_ENGAGEMENT_ONSITE_PHOTO_FILE_TITLE_PREFIX + '_' + staticTestData.get('fellowshipYear') + '_' + staticTestData.get('firstName') + '_' + staticTestData.get('lastName') + '_'
            },
            5, true);
        List<ContentDocumentLink> onsitePhotosCDL = TestFactory.createMultipleContentDocumentLinks(onsitePhotosCV, null, ce.Id, null, true);


        ContentDocumentLink cdlRetr = TestFactory.retrieveContentDocumentLink(
            new Map<String, Object> {
                'LinkedEntityId' => '\'' + ce.Id + '\'',
                'ContentDocument.LatestPublishedVersion.Deleted_By_Fellow__c' => false
            },
            new List<String> {
                'ContentDocument.CreatedDate',
                'ContentDocument.LastModifiedDate',
                'ContentDocument.Title',
                'ContentDocument.ContentSize',
                'ContentDocument.FileType',
                'ContentDocument.LatestPublishedVersion.Deleted_By_Fellow__c',
                'ContentDocument.LatestPublishedVersionId'
            },
            new List<String> {
                'ContentDocument.LastModifiedDate DESC'
            });
        System.debug('cdlList: in test class::'+cdlRetr);
        System.debug('record id in test class::'+ce.id);

        //need to delete later just for debuging
        User u = TestFactory.createUser(staticTestData.get('email'), 'Fellow Portal Community User', staticTestData.get('firstName'), staticTestData.get('lastName'), c.Id, null, true);
        User usr = TestFactory.retrieveUser(new Map<String, Object> {
                'Email' => '\'' + staticTestData.get('email') + '\''
            }, null, null);
        System.debug('User in TESTSETUP ::' + u);
        System.debug('User retrieved in TESTSETUP ::' + usr);
    }

}