force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>For Households, Head of Household Contact&apos;s Primary Email. For Organizations, email for the org as a whole.</description>
    <inlineHelpText>For Households, Head of Household Contact&apos;s Primary Email. For Organizations, email for the org as a whole.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact_Email__c/Contact_Email__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold the emails related to a Contact.</description>
    <label>Contact Email</label>
    <nameField>
        <displayFormat>CE-{000000}</displayFormat>
        <label>Email ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Emails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Email__c/fields/Created_from_Fellow_App__c.field-meta.xml
<CustomField>
    <fullName>Created_from_Fellow_App__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created from Fellow App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Emails</relationshipLabel>
    <relationshipName>Contact_Emails</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Current&quot;</defaultValue>
    <description>Status of email on record.</description>
    <inlineHelpText>Indicates if email is current or former.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
                <isActive>false</isActive>
                <label>Former</label>
            </value>
            <value>
                <fullName>Former_Archived</fullName>
                <isActive>false</isActive>
                <label>Former_Archived</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Email__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold the phone numbers related to a Contact.</description>
    <label>Contact Phone</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Phone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Created_from_Fellow_App__c.field-meta.xml
<CustomField>
    <fullName>Created_from_Fellow_App__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Created from Fellow App</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Phones</relationshipLabel>
    <relationshipName>Contact_Phones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Phone number status.</description>
    <inlineHelpText>Indicate status of this phone number.</inlineHelpText>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Undeliverable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Additional Home</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant Mobile</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/CC_Year__c.field-meta.xml
<CustomField>
    <fullName>CC_Year__c</fullName>
    <label>CC Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordId__c/RecordId__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Record Ids</label>
</CustomObject>

force-app/main/default/objects/RecordId__c/fields/IdValue__c.field-meta.xml
<CustomField>
    <fullName>IdValue__c</fullName>
    <label>IdValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/States__c/States__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of states displayed on Fellow Application on Portal</description>
    <label>States</label>
</CustomObject>

force-app/main/default/classes/EDF28_RegisterController_Test.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 3/14/2022
# Last Modified by......:  
# Last Modified Date....: 
# Description...........: Test class for EDF28_RegisterController 
# Change Log:               
#
#
############################################################################
*/
@isTest
public class EDF28_RegisterController_Test {
    
@testsetup
    public static void createTestData() {
        createCustomSettingData();
    }
    
    static testMethod void testCreateContact() {
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060' ); insert c; 
        Fellow_Application__c fa = new Fellow_Application__c(Applicant__c=c.Id,Status__c='Engagement Confirmed'); insert fa;
        Profile p = [SELECT Id FROM Profile WHERE Name='Fellow Portal Community User'];
        User u = new User(Alias = 'standt', Email='someone@abc.bix', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id,isActive = false, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='someone@abc.bix.edf', FirstName='TestFN', ContactId=c.Id);
        insert u;
        EDF28_RegisterController.isEmailExists(c.Email);
        EDF28_RegisterController.getCountries();
        EDF28_RegisterController.getStatesByCountry(c.MailingCountry);
        EDF28_RegisterController.saveUser(c, c.Email);
        Contact_Wrapper cw=new Contact_Wrapper();
         Contact_Wrapper cwr=new Contact_Wrapper(String.valueOf(c.Id));
        	
        Contact_Email__c contactEmail=new Contact_Email__c(Donor__c=c.Id,Type__c='Personal',Email__c='someone@abc.bix',Status__c='Current');
        insert contactEmail;
        Contact_Phone__c contactPhone=new Contact_Phone__c(Donor__c=c.Id,Type__c='Home',Phone__c='9876543210',Status__c='Current');
        insert contactPhone;
        Contact_Wrapper cw2=new Contact_Wrapper(c,contactEmail,contactPhone);
        	cw2.getContact();
            cw2.getFirstName();
            cw2.getLastName();
            cw2.getEmail();
            cw2.getPhone();
            cw2.getContactPhone();
            cw2.getMailingStreet();
            cw2.getStreetAddressLine2();
            cw2.getStreetAddress();
            cw2.getId();
            cw2.getAccountId();
    }
    static testMethod void testWrapper() {
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c; 
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='someone@abc.bix', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id,isActive = true, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='someone@abc.bix.edf', FirstName='TestFN');
        insert u;
        system.runAs(u){
            UserRole roleId = new UserRole(DeveloperName = 'Administrators',Name = 'Administrators');
        insert roleId;
            u.UserRoleId = roleId.Id;
            update u; 
        }
        
        EDF28_RegisterController.PayloadWrapper pw = new EDF28_RegisterController.PayloadWrapper();
        pw.firstName='test';
        pw.LastName='TestLN';
        pw.Email='someone@abc1.bix';
        pw.Phone='9876543210';
        pw.country = 'India';
        pw.state = 'Delhi';
        pw.City='New Delhi';
        pw.PostalCode='110060';
        pw.address1 = 'test';
        pw.address2 = 'test';
        try{
            EDF28_RegisterController.registerFellow(pw);
        }
        catch(Exception e){
            
        }
        EDF28_RegisterController.saveContact('sys');  
        EDF28_RegisterController.createUser(c.Id, c.email, c.firstName, c.lastName, c.email, '', c.LastName.substring(0, 3), true, a.Id);
    }
    
    static testMethod void testcheckUser() {
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c; 
        Contact_Email__c ce = new Contact_Email__c(Donor__c = c.Id,Email__c = c.Email,Created_from_Fellow_App__c = true, Primary__c = TRUE); insert ce;
        Fellow_Application__c fa = new Fellow_Application__c(Applicant__c=c.Id,Status__c='Engagement Confirmed',CC_Year__c  = '2022'); insert fa;
        Profile p = [SELECT Id FROM Profile WHERE Name='Fellow Portal Community User'];
        User u = new User(Alias = 'standt', Email=c.Email, 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id,IsActive = true, 
                          TimeZoneSidKey='America/Los_Angeles', UserName=c.Email, FirstName='TestFN', ContactId=c.Id);
        insert u;
        EDF28_RegisterController.forgotPassword(u.Email) ;
        EDF28_RegisterController.isEmailExists(c.Email);
        EDF28_RegisterController.isFellowAppExist(c.Email, '2022', c.Id);
        EDF28_RegisterController.updateContactEmail(ce);
        EDF28_RegisterController.updateContactRecord(c);
        EDF28_RegisterController.futureUpdateActivateUser(u.id,u.Username,u.IsActive);
        
    }
    
    public static void createCustomSettingData() {
        List<RecordId__c> recordIdCustomSetting = new List<RecordId__c>();
        if(RecordId__c.getAll().get('DefaultOwnerId') == NULL){
            recordIdCustomSetting.add(new RecordId__c(name = 'DefaultOwnerId',IdValue__c = string.valueOf(UserInfo.getUserId())));
        }
        if(recordIdCustomSetting.size()>0){
            insert recordIdCustomSetting;
        } 
        List<States__c> stateCSList = new List<States__c>();
        stateCSList.add(new States__c(Name='CA', Country__c='United States'));
        stateCSList.add(new States__c(Name='IL', Country__c='United States'));
        stateCSList.add(new States__c(Name='Haryana', Country__c='India'));
        stateCSList.add(new States__c(Name='Delhi', Country__c='India'));
        stateCSList.add(new States__c(Name='Beijing', Country__c='China'));
        stateCSList.add(new States__c(Name='Hongkong', Country__c='China'));
        insert stateCSList;
    }
    
}