force-app/main/default/objects/Account/fields/Organization_Constituency__c.field-meta.xml
<CustomField>
    <fullName>Organization_Constituency__c</fullName>
    <label>Constituency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constituency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Organization_sub_constituency__c.field-meta.xml
<CustomField>
    <fullName>Organization_sub_constituency__c</fullName>
    <label>Sub-constituency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sub_Constituency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <description>Heller created 2021</description>
    <label>Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Family</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Non-profit</fullName>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Public Charity</fullName>
            </value>
            <value>
                <fullName>School</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Operating Foundation</fullName>
            </value>
            <value>
                <fullName>Corporate Foundation</fullName>
            </value>
            <value>
                <fullName>Combined Campaign</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Organization.recordType-meta.xml
<RecordType>
    <fullName>Organization</fullName>
    <active>true</active>
    <description>An Account representing an organization</description>
    <label>Organization</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Date_Expected_Graduated_1__c.field-meta.xml
<CustomField>
    <fullName>Date_Expected_Graduated_1__c</fullName>
    <label>GRAD Expected Graduation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Degree_Earned_2__c.field-meta.xml
<CustomField>
    <fullName>Degree_Earned_2__c</fullName>
    <label>UG Degree(s)</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Associate of Applied Science (AAS)</fullName>
            </value>
            <value>
                <fullName>Associate of Arts (AA)</fullName>
            </value>
            <value>
                <fullName>Associate of Science (AS)</fullName>
            </value>
            <value>
                <fullName>Bachelor of Arts (BA)</fullName>
            </value>
            <value>
                <fullName>Bachelor of Science (BS)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Dual_Degree_School_Name__c.field-meta.xml
<CustomField>
    <fullName>Dual_Degree_School_Name__c</fullName>
    <label>GRAD University DualDegree if not listed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_Degree_Concentration__c.field-meta.xml
<CustomField>
    <fullName>GRAD_Degree_Concentration__c</fullName>
    <label>Graduate Degree Concentration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_Degree_s_if_not_listed__c.field-meta.xml
<CustomField>
    <fullName>GRAD_Degree_s_if_not_listed__c</fullName>
    <label>GRAD Degree(s), if not listed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_Degree_s_pursuing__c.field-meta.xml
<CustomField>
    <fullName>GRAD_Degree_s_pursuing__c</fullName>
    <label>GRAD Degree(s) pursuing</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Graduate Certificate</fullName>
            </value>
            <value>
                <fullName>Juris Doctor(JD)</fullName>
            </value>
            <value>
                <fullName>Master of Architecture (M.Arch)</fullName>
            </value>
            <value>
                <fullName>Master of Arts (MA)</fullName>
            </value>
            <value>
                <fullName>Master of Science (MS)</fullName>
            </value>
            <value>
                <fullName>Master of Business Admin(MBA)</fullName>
            </value>
            <value>
                <fullName>Master of Engineering(MEng.)</fullName>
            </value>
            <value>
                <fullName>Master of Environmental Management(MEM)</fullName>
            </value>
            <value>
                <fullName>Master of Environmental Science</fullName>
            </value>
            <value>
                <fullName>Master of Fine Arts (MFA)</fullName>
            </value>
            <value>
                <fullName>Master of Liberal Arts</fullName>
            </value>
            <value>
                <fullName>Master of Public Admin (MPA)</fullName>
            </value>
            <value>
                <fullName>Master of Public Policy (MPP)</fullName>
            </value>
            <value>
                <fullName>Master of Technology</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_Dual_Degree_School_in_University__c.field-meta.xml
<CustomField>
    <fullName>GRAD_Dual_Degree_School_in_University__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Heller created 2021</description>
    <label>GRAD Dual Degree School in University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fellow Applications (GRAD Dual Degree School in University)</relationshipLabel>
    <relationshipName>Fellow_Applications2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_School_within_University__c.field-meta.xml
<CustomField>
    <fullName>GRAD_School_within_University__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Heller created 2021</description>
    <label>GRAD School within University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fellow Applications (GRAD School within University)</relationshipLabel>
    <relationshipName>Fellow_Applications3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/GRAD_University_Dual_Degree__c.field-meta.xml
<CustomField>
    <fullName>GRAD_University_Dual_Degree__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRAD University - Dual Degree</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fellow Applications (GRAD University - Dual Degree)</relationshipLabel>
    <relationshipName>Fellow_Applications_GRAD_University_Dual</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Graduation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Graduation_Start_Date__c</fullName>
    <label>Graduate Degree Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Other_courses_certifications__c.field-meta.xml
<CustomField>
    <fullName>Other_courses_certifications__c</fullName>
    <label>Other course(s) and certification(s)</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/UG_Degree_s_if_not_listed__c.field-meta.xml
<CustomField>
    <fullName>UG_Degree_s_if_not_listed__c</fullName>
    <label>UG Degree(s), if not listed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Undergrad_Major__c.field-meta.xml
<CustomField>
    <fullName>Undergrad_Major__c</fullName>
    <label>Undergrad Major</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/University_Other_1__c.field-meta.xml
<CustomField>
    <fullName>University_Other_1__c</fullName>
    <label>GRAD University, if not listed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/University_Other_2__c.field-meta.xml
<CustomField>
    <fullName>University_Other_2__c</fullName>
    <label>UG University, if not listed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/University_School_1__c.field-meta.xml
<CustomField>
    <fullName>University_School_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Heller created 2021</description>
    <label>Grad University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fellow Applications</relationshipLabel>
    <relationshipName>Fellow_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/University_School_2__c.field-meta.xml
<CustomField>
    <fullName>University_School_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Heller created 2021</description>
    <label>UG University</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fellow Applications (UG University)</relationshipLabel>
    <relationshipName>Fellow_Applications1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UniversityHelper.cls
public without sharing class UniversityHelper {

    /**
    * Description : This method returns the Accounts whose record type is organization and parent equal to null.
    **/
    @AuraEnabled(cacheable=true)
    public static List<Account> retrieveUniversityAccounts() {
        List<Account> univList
            = [SELECT Name, Id
                FROM Account
                WHERE RecordType.DeveloperName = 'Organization'
                    AND Type = 'Organization'
                    AND Organization_Constituency__c INCLUDES ('EDFBIZ')
                    AND Organization_sub_constituency__c INCLUDES ('EDFBIZ - Climate Corps')
                    AND Sub_Type__c = 'School'
                    AND ParentId = null // Condition added by Harpreet 8/22/2020
                ORDER BY Name];
                System.debug('univList:'+univList);
        return univList;
    }
    /**
    * Description : This method returns the Accounts whose record type is organization and parent not equal to null.
    **/
    @AuraEnabled(cacheable=true)
    public static List<Account> retrieveUniversitySchoolAccounts(String parentId) {
        System.debug('parentId:'+parentId);
        List<Account> univList
            = [SELECT Name, Id
                FROM Account
                WHERE RecordType.DeveloperName = 'Organization'
                    AND Type = 'Organization'
                    AND Organization_Constituency__c INCLUDES ('EDFBIZ')
                    AND Organization_sub_constituency__c INCLUDES ('EDFBIZ - Climate Corps')
                    AND Sub_Type__c = 'School'
                    AND ParentId = :parentId
                ORDER BY Name];
                System.debug('univList:Child'+univList);
        return univList;
    }

    @AuraEnabled(cacheable=true)
    public static List<Account> retrieveUniversitySchoolAccountsWithParents() {
        List<Account> univList
            = [SELECT Name, Id
                FROM Account
                WHERE RecordType.DeveloperName = 'Organization'
                    AND Type = 'Organization'
                    AND Organization_Constituency__c INCLUDES ('EDFBIZ')
                    AND Organization_sub_constituency__c INCLUDES ('EDFBIZ - Climate Corps')
                    AND Sub_Type__c = 'School'
                    AND ParentId != null
                ORDER BY Name];
        return univList;
    }


    @AuraEnabled
    public static Fellow_Application__c updateEducationInformation(Fellow_Application__c fa) {
        System.debug('UniversityHelper :: updateEducationInformation :: fa ::' + fa);
        Fellow_Application__c fApp = new Fellow_Application__c();
        fApp.Id = fa.Id;
        fApp.University_School_1__c = fa.University_School_1__c;
        fApp.GRAD_School_within_University__c = fa.GRAD_School_within_University__c;
        fApp.University_Other_1__c = fa.University_Other_1__c;
        fApp.GRAD_University_Dual_Degree__c = fa.GRAD_University_Dual_Degree__c;
        fApp.GRAD_Dual_Degree_School_in_University__c = fa.GRAD_Dual_Degree_School_in_University__c;
        fApp.Dual_Degree_School_Name__c = fa.Dual_Degree_School_Name__c;
        fApp.GRAD_Degree_s_pursuing__c = fa.GRAD_Degree_s_pursuing__c;
        fApp.GRAD_Degree_s_if_not_listed__c = fa.GRAD_Degree_s_if_not_listed__c;
        fApp.GRAD_Degree_Concentration__c = fa.GRAD_Degree_Concentration__c;
        fApp.Graduation_Start_Date__c = fa.Graduation_Start_Date__c;
        fApp.Date_Expected_Graduated_1__c = fa.Date_Expected_Graduated_1__c;
        fApp.University_School_2__c = fa.University_School_2__c;
        fApp.University_Other_2__c = fa.University_Other_2__c;
        fApp.Degree_Earned_2__c = fa.Degree_Earned_2__c;
        fApp.UG_Degree_s_if_not_listed__c = fa.UG_Degree_s_if_not_listed__c;
        fApp.Undergrad_Major__c = fa.Undergrad_Major__c;
        fApp.Other_courses_certifications__c = fa.Other_courses_certifications__c;
        update fApp;
        return fApp;
    }
}