force-app/main/default/objects/Contact/fields/CC_Alumni_Group_Member__c.field-meta.xml
<CustomField>
    <fullName>CC_Alumni_Group_Member__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Member of the Climate Corps alumni Linkedin group.</inlineHelpText>
    <label>CC Alumni Group Member</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/On_EDF_Connect_Platform__c.field-meta.xml
<CustomField>
    <fullName>On_EDF_Connect_Platform__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On EDF Connect Platform</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Permanent_Street_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Street_Address_Line_2__c</fullName>
    <label>Permanent Street Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Skype__c.field-meta.xml
<CustomField>
    <fullName>Skype__c</fullName>
    <label>Skype</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Do_you_identify_as_Latinx_or_Hispanic__c.field-meta.xml
<CustomField>
    <fullName>Do_you_identify_as_Latinx_or_Hispanic__c</fullName>
    <label>Do you identify as Latinx or Hispanic?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Fellowship_Applying_for__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Applying_for__c</fullName>
    <label>Fellowship Applying for?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_Campus_Presentation__c.field-meta.xml
<CustomField>
    <fullName>How_Campus_Presentation__c</fullName>
    <label>How you learnt about Campus Presentation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eventbrite Invitation</fullName>
            </value>
            <value>
                <fullName>Other online event site</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Other social media site</fullName>
            </value>
            <value>
                <fullName>Student group announcement</fullName>
            </value>
            <value>
                <fullName>Campus career services announcement</fullName>
            </value>
            <value>
                <fullName>School program communication</fullName>
            </value>
            <value>
                <fullName>Bulletin board posting</fullName>
            </value>
            <value>
                <fullName>Former fellow communication</fullName>
            </value>
            <value>
                <fullName>Former host organization communication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_did_find_out_about_EDF_Other__c.field-meta.xml
<CustomField>
    <fullName>How_did_find_out_about_EDF_Other__c</fullName>
    <label>If other, how did you find out about EDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_Did_You_Find_Us__c.field-meta.xml
<CustomField>
    <fullName>How_Did_You_Find_Us__c</fullName>
    <description>Could be Picklist</description>
    <label>How did you find out about EDFCC?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Campus Presentation with EDF staff</fullName>
            </value>
            <value>
                <fullName>EDF Staff webinar</fullName>
            </value>
            <value>
                <fullName>Career services job posting</fullName>
            </value>
            <value>
                <fullName>Career Services staff</fullName>
            </value>
            <value>
                <fullName>EDF website</fullName>
            </value>
            <value>
                <fullName>Student group newsletter</fullName>
            </value>
            <value>
                <fullName>Word of Mouth  from an Alumni Fellow</fullName>
            </value>
            <value>
                <fullName>Word of Mouth from another source</fullName>
            </value>
            <value>
                <fullName>Online Job postings (e.g, indeed.com, idealist.org, greenbiz.com)</fullName>
            </value>
            <value>
                <fullName>National Black MBA Conference</fullName>
            </value>
            <value>
                <fullName>Prospanica conference</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Pronouns__c.field-meta.xml
<CustomField>
    <fullName>Pronouns__c</fullName>
    <label>Pronouns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>He/Him/His</fullName>
            </value>
            <value>
                <fullName>She/Her/Hers</fullName>
            </value>
            <value>
                <fullName>They/Them/Theirs</fullName>
            </value>
            <value>
                <fullName>Prefer to self-describe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Pronouns_Self_Describe__c.field-meta.xml
<CustomField>
    <fullName>Pronouns_Self_Describe__c</fullName>
    <label>Pronouns Self Describe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Indian or Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black/African American</fullName>
            </value>
            <value>
                <fullName>Pacific Islander</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Returner_Fellow__c.field-meta.xml
<CustomField>
    <fullName>Returner_Fellow__c</fullName>
    <inlineHelpText>Have you participated in the Climate Corps program in the past?</inlineHelpText>
    <label>Returner Fellow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Genderqueer</fullName>
            </value>
            <value>
                <fullName>Man</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
            <value>
                <fullName>Woman</fullName>
            </value>
            <value>
                <fullName>Prefer to self-describe</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Sex_Self_Describe__c.field-meta.xml
<CustomField>
    <fullName>Sex_Self_Describe__c</fullName>
    <description>Provide a description for Gender if Prefer to Self-Describe is selected.</description>
    <label>Sex Self Describe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Skype__c.field-meta.xml
<CustomField>
    <fullName>Skype__c</fullName>
    <label>Skype</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Veteran_Status__c.field-meta.xml
<CustomField>
    <fullName>Veteran_Status__c</fullName>
    <inlineHelpText>Classification of Protected Veteran - 
Disabled veteran
Recently separated veteran
Active duty wartime or campaign badge veteran
Armed forces service medal veteran</inlineHelpText>
    <label>Veteran Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I identify as one or more of the classifications of protected veteran</fullName>
            </value>
            <value>
                <fullName>I am not a protected veteran</fullName>
            </value>
            <value>
                <fullName>I decline to self-identify</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EdfContactController.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 1/2/2022
# Last Modified by......:
# Last Modified Date....:
# Description...........: This Class contains Edit Contact Info Related functinality.
# Test Class............: EdfContactController_Test
# Change Log:
#
############################################################################
*/
public with sharing class EdfContactController {
	/**
    * Description : This method returns the Contact of the current loggin user associated record.
    **/
    @AuraEnabled (cacheable=true)
    public static ContactWrapper getContactForEDF(){
        return EdfContactController.getContact();
    }

    @AuraEnabled
    public static ContactWrapper getContact(){
        ContactWrapper cw = new ContactWrapper();
        String contactId = getContactId();
        Contact contact = [SELECT Id, Name, FirstName, LastName, Email,Phone, MailingStreet, Permanent_Street_Address_Line_2__c, MailingCity, MailingState, MailingCountry, MailingPostalCode, Resume__c, CC_Alumni_Group_Member__c, On_EDF_Connect_Platform__c FROM Contact WHERE Id =:contactId];

        // if(contact !=null)
        // {
            cw.id = contact.id;
            cw.firstName = contact.FirstName;
            cw.lastName = contact.LastName;
            cw.email = contact.Email;
            cw.phone = contact.Phone;
            cw.permanentStreetAddressLine1 = contact.MailingStreet;
            cw.permanentStreetAddressLine2 = contact.Permanent_Street_Address_Line_2__c;
            cw.mailingState = contact.MailingState;
            cw.mailingCity = contact.MailingCity;
            cw.mailingCountry = contact.MailingCountry;
            cw.mailingPostalCode = contact.MailingPostalCode;
            cw.countryPickListValues = getCountryPickListValues();
            if(!String.isBlank(contact.MailingCountry)){
                cw.statePickListValues = getStatePickListValuesByCountry(contact.MailingCountry);
            }
            else {
                cw.statePickListValues = getStatePickListValues();
            }
            cw.resume = contact.Resume__c;
            // cw.ccAlumniGrpMember = contact.CC_Alumni_Group_Member__c;
            // cw.onEdfConnectPlat = contact.On_EDF_Connect_Platform__c;
            cw.CC_Alumni_Group_Member = contact.CC_Alumni_Group_Member__c;
            cw.On_EDF_Connect_Platform = contact.On_EDF_Connect_Platform__c;
            cw.fellowApplicationId = getfellowApplicationId(contact.id);
        // }
        System.debug('EdfContactController getContact() :::' + cw);
        return cw;
    }
	/**
    * Description : This method returns the Contact of the current loggin user associated record.
    **/
    @AuraEnabled
    public static string updateContact(ContactWrapper contactWrapper){
        try {
            Id recordId = Id.valueOf(contactWrapper.id);
            Contact contact = [SELECT Id, Name, FirstName, LastName, Email,Phone, MailingStreet,Permanent_Street_Address_Line_2__c, MailingCity, MailingState, MailingCountry,MailingPostalCode,Resume__c FROM Contact WHERE Id =:recordId LIMIT 1];

             //if(contactList.size()>0){
                //for(Contact contact : contactList){
                    contact.FirstName = contactWrapper.firstName;
                    contact.LastName = contactWrapper.lastName;
                    contact.Email = contactWrapper.email;
                    contact.Phone = contactWrapper.phone;
                    contact.MailingStreet = contactWrapper.permanentStreetAddressLine1;
                    contact.Permanent_Street_Address_Line_2__c = contactWrapper.permanentStreetAddressLine2;
                    contact.MailingState = contactWrapper.mailingState;
                    contact.MailingCity = contactWrapper.mailingCity;
                    contact.MailingCountry = contactWrapper.mailingCountry;
                    contact.MailingPostalCode = contactWrapper.mailingPostalCode;
                    contact.Resume__c = contactWrapper.resume;
                 //}

                 upsert contact;
                 return 'contactWrapper.mailingCity:' + contactWrapper.mailingCity;
            //}

        }
        catch (Exception e) {
            //return 'Not updated';
            return e.getMessage();
        }
    }
	/**
    * Description : This method return the Fellow ApplicationId.
    **/

    @AuraEnabled
    public static string updateFellowApplication(FellowAppWrapper fellowAppWrapper){
        Boolean fellowAppSave = false;
        Boolean contactSave = false;
        // try {
            Id fellowAppId = Id.valueOf(fellowAppWrapper.fellowApplicationId);
            Id contactId = Id.valueOf(fellowAppWrapper.contactId);
            Fellow_Application__c[] fellowApps = [SELECT Id,
                                                Fellowship_Applying_for__c,
                                                Pronouns__c,
                                                Pronouns_Self_Describe__c,
                                                How_Did_You_Find_Us__c,
                                                How_did_find_out_about_EDF_Other__c,
                                                Returner_Fellow__c,
                                                Sex__c,
                                                Skype__c,
                                                Sex_Self_Describe__c,
                                                Race__c,
                                                Do_you_identify_as_Latinx_or_Hispanic__c,
                                                Veteran_Status__c,
                                                Applicant__c
                                            FROM
                                                Fellow_Application__c
                                            WHERE
                                                Id  =:fellowAppId];

            Contact[] contacts = [SELECT Id, Name, FirstName, LastName, Email,Phone, MailingStreet,Permanent_Street_Address_Line_2__c, MailingCity, MailingState, MailingCountry,MailingPostalCode FROM Contact WHERE Id =:contactId];

            if (fellowApps != null  &&  fellowApps.size() > 0){

                Fellow_Application__c fellowApp = fellowApps.get(0);

                fellowApp.Fellowship_Applying_for__c = fellowAppWrapper.fellowshipApplyingFor;
                fellowApp.Pronouns__c = fellowAppWrapper.pronouns;
                fellowApp.Pronouns_Self_Describe__c = fellowAppWrapper.pronounsSelfDescribe;
                fellowApp.How_Did_You_Find_Us__c = fellowAppWrapper.howDidYouFindUs;
                fellowApp.How_did_find_out_about_EDF_Other__c = fellowAppWrapper.howDidYouFindUsIfOther;
                fellowApp.Skype__c = fellowAppWrapper.skypeID;
                fellowApp.Returner_Fellow__c = fellowAppWrapper.returnerFellow;
                fellowApp.Sex__c = fellowAppWrapper.gender;
                fellowApp.Sex_Self_Describe__c = fellowAppWrapper.genderSelfDescribe;
                fellowApp.Race__c = fellowAppWrapper.race;
                fellowApp.Do_you_identify_as_Latinx_or_Hispanic__c = fellowAppWrapper.latinxOrHispanic;
                fellowApp.Veteran_Status__c = fellowAppWrapper.veteranStatus;

                update fellowApp;

                fellowAppSave = true;
            }

            if (contacts != null  &&  contacts.size() > 0){

                Contact contact = contacts.get(0);

                contact.FirstName = fellowAppWrapper.firstName;
                contact.LastName = fellowAppWrapper.lastName;
                contact.Email = fellowAppWrapper.email;
                contact.Phone = fellowAppWrapper.phone;
                contact.MailingCountry = fellowAppWrapper.mailingCountry;
                contact.MailingPostalCode = fellowAppWrapper.mailingPostalCode;
                contact.MailingState = fellowAppWrapper.mailingState;
                contact.MailingCity = fellowAppWrapper.mailingCity;
                contact.MailingStreet = fellowAppWrapper.permanentStreetAddressLine1;
                contact.Permanent_Street_Address_Line_2__c = fellowAppWrapper.permanentStreetAddressLine2;

                update contact;

                contactSave = true;
            }

            if(fellowAppSave && contactSave){
                return 'success';
            }

        // }
        // catch (Exception e) {
        //     //return 'Not updated';
        //     return e.getMessage();
        // }

        return 'fellowAppSave:' + fellowAppSave + '  contactSave: ' + contactSave + '  fellowAppId:' + fellowAppId;
    }
	/**
    * Description : This method returns the Countries in sorted order from 'Countries__c' custom settings.
    **/
    public static List<String> getCountryPickListValues(){
        // List<String> pickListValues= new List<String> {'USA', 'India', 'United Kingdom', 'Canada', 'China', 'Australia'};
        //  return pickListValues;

        List<String> pickListValues = new List<String>(Countries__c.getAll().keyset());
        pickListValues.sort();

        return pickListValues;
     }
    /**
    * Description : This method returns the states in sorted order from 'States__c' custom settings.
    **/
    public static List<String> getStatePickListValues(){
        // List<String> pickListValues= new List<String>{'Andhra Pradesh', 'Telangana','Tamil Nadu','Arunachal Pradesh', 'Maharashtra', 'Punjab'};
        // return pickListValues;

        List<String> pickListValues = new List<String>(States__c.getAll().keyset());
        pickListValues.sort();
        return pickListValues;
    }
	/**
    * Description : This method returns the states based on the country values selected.
    **/
    @AuraEnabled
    public static List<String> getStatePickListValuesByCountry(string country){
        List<String> pickListValues = new List<String>();
        if(!String.isBlank(country)){
            // Find all the states we have in custom settings.
            Map<String, States__c> allstates = States__c.getAll();
            // Filter states that belong to the selected country
            for(States__c state : allstates.values()) {
                if (state.Country__c == country) {
                    pickListValues.add(state.name);
                }
            }
        }

        if(pickListValues.size() > 0){
            pickListValues.sort();
        }

        return pickListValues;
    }
    /**
    * Description : This method returns the fellowapplication record in the form of FellowAppWrapper.
    **/
    @AuraEnabled
    public static FellowAppWrapper getContactInfo(){

        FellowAppWrapper fw = new FellowAppWrapper();
        String contactId = getContactId();
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
		List<string> mailingStreets = new List<string>();
        Fellow_Application__c[]  fellowApps = [SELECT Id,
                                Applicant__c,
                                Applicant__r.Name,
                                Applicant__r.FirstName,
                                Applicant__r.LastName,
                                Applicant__r.Email,
                                Applicant__r.Phone,
                                Applicant__r.MailingStreet,
                                Applicant__r.Permanent_Street_Address_Line_2__c,
                                Applicant__r.MailingCity,
                                Applicant__r.MailingState,
                                Applicant__r.MailingCountry,
                                Applicant__r.MailingPostalCode,
                                Pronouns__c,
                                Pronouns_Self_Describe__c,
                                Fellowship_Applying_for__c,
                                Skype__c,
                                How_Did_You_Find_Us__c,
                                How_Campus_Presentation__c,
                                How_did_find_out_about_EDF_Other__c,
                                Returner_Fellow__c,
                                Sex__c,
                                Sex_Self_Describe__c,
                                Race__c,
                                Do_you_identify_as_Latinx_or_Hispanic__c,
                                Veteran_Status__c
                            FROM
                                Fellow_Application__c
                            WHERE
                                Applicant__c  =:contactId AND CC_Year__c=:fellowshipYear];

        // if (fellowApps != null  &&  fellowApps.size() > 0){
        // {
            Fellow_Application__c fellowApp = fellowApps.get(0);
            fw.id = fellowApp.Id;
            fw.fellowApplicationId = fellowApp.Id;
            fw.contactId = fellowApp.Applicant__c;
            fw.firstName = fellowApp.Applicant__r.FirstName;
            fw.lastName = fellowApp.Applicant__r.LastName;
            fw.email = fellowApp.Applicant__r.Email;
            fw.phone = fellowApp.Applicant__r.Phone;
            if(fellowApp.Applicant__r.MailingStreet!=null && fellowApp.Applicant__r.MailingStreet.contains(',')){
                mailingStreets = fellowApp.Applicant__r.MailingStreet.split(',');
                System.debug('mailingStreets:'+mailingStreets);
                if(mailingStreets.size()>1){
                    fw.permanentStreetAddressLine1 = mailingStreets[0];
                    fw.permanentStreetAddressLine2 = mailingStreets[1]=='null'?'':mailingStreets[1];
                }
                else {
                    fw.permanentStreetAddressLine1 = fellowApp.Applicant__r.MailingStreet;
                }
            }
            else{
                fw.permanentStreetAddressLine1 = fellowApp.Applicant__r.MailingStreet;
            }
            fw.mailingState = fellowApp.Applicant__r.MailingState;
            fw.mailingCity = fellowApp.Applicant__r.MailingCity;
            fw.mailingCountry = fellowApp.Applicant__r.MailingCountry;
            fw.mailingPostalCode = fellowApp.Applicant__r.MailingPostalCode;
            fw.countryPickListValues = getCountryPickListValues();
            if(!String.isBlank(fellowApp.Applicant__r.MailingCountry)){
                fw.statePickListValues = getStatePickListValuesByCountry(fellowApp.Applicant__r.MailingCountry);
            }
            else {
                fw.statePickListValues = getStatePickListValues();
            }
            fw.fellowshipApplyingFor = fellowApp.Fellowship_Applying_for__c;
            fw.pronouns = fellowApp.Pronouns__c;
            fw.pronounsSelfDescribe = fellowApp.Pronouns_Self_Describe__c;
            fw.howDidYouFindUs = fellowApp.How_Did_You_Find_Us__c;
            fw.skypeID = fellowApp.Skype__c;
            fw.howDidYouFindUsIfOther = fellowApp.How_did_find_out_about_EDF_Other__c;
            fw.returnerFellow = fellowApp.Returner_Fellow__c;
            fw.gender = fellowApp.Sex__c;
            fw.genderSelfDescribe = fellowApp.Sex_Self_Describe__c;
            fw.race = fellowApp.Race__c;
            fw.latinxOrHispanic = fellowApp.Do_you_identify_as_Latinx_or_Hispanic__c;
            fw.veteranStatus = fellowApp.Veteran_Status__c;
            fw.fellowApplicationId = fellowApp.Id;

            return fw;

        //  }

        //return fw;
    }
	/**
    * Description : This method returns the fellowship appling for pick list values.
    **/
    public static List<String> getFellowshipApplyingForPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.Fellowship_Applying_for__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;
     }
	/**
    * Description : This method returns the HowDidYouFindUs pick list values.
    **/
     public static List<String> getHowDidYouFindUsPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.How_Did_You_Find_Us__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;

     }
	/**
    * Description : This method returns the ReturnerFellow pick list values.
    **/
     public static List<String> getReturnerFellowPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.Returner_Fellow__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;

     }
	/**
    * Description : This method returns the Gender pick list values.
    **/
     public static List<String> getGenderPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.Sex__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;

     }
	/**
    * Description : This method returns the DoYouIdentifyAsLatinxOrHispanic pick list values.
    **/
     public static List<String> getDoYouIdentifyAsLatinxOrHispanicPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.Do_you_identify_as_Latinx_or_Hispanic__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;

     }
	/**
    * Description : This method returns the VeteranStatus pick list values.
    **/
     public static List<String> getVeteranStatusPickListValues(){
        List<String> pickListValuesList= new List<String>();
         Schema.DescribeFieldResult fieldResult = Fellow_Application__c.Veteran_Status__c.getDescribe();
         List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
         for( Schema.PicklistEntry pickListVal : ple){
             pickListValuesList.add(pickListVal.getLabel());
         }
         return pickListValuesList;

     }
	/**
    * Description : This method returns the current logged in User Associated Contact ID.
    **/
    public static String getContactId() {
        String contactId = '';
        String currUserId = Userinfo.getUserId();
        User[] users = [SELECT Id, FirstName, LastName, Contact.Name, username, ContactId, email
                        FROM User WHERE Id = :currUserId and ContactId <> null];
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            contactId = user.ContactId;
        }

        return contactId;

    }
	/**
    * Description : This method returns the Associated fellowApplication ID with respect to contactId.
    **/
    public static String getfellowApplicationId(String contactId) {
        String fellowApplicationId = '';
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        List<Fellow_Application__c> fellowAppList = [SELECT Id,
                                Applicant__c,
                                Status__c
                            FROM
                                Fellow_Application__c
                            WHERE
                                Applicant__c  = :contactId AND CC_Year__c=:fellowshipYear LIMIT 1];
        if(!fellowAppList.isEmpty()){
            fellowApplicationId = fellowAppList[0].Id;
        }

        return fellowApplicationId;

    }
	/**
    * Description : This method returns the current logged in User Associated fellowApplication ID.
    **/
    @AuraEnabled(cacheable=true)
    public static String getfellowAppId() {
        String fellowApplicationId = '';
        String contactId = getContactId();
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        List<Fellow_Application__c> fellowAppList = [SELECT Id,
                                Applicant__c,
                                Status__c
                            FROM
                                Fellow_Application__c
                            WHERE
                                Applicant__c  = :contactId AND CC_Year__c=:fellowshipYear LIMIT 1];
        if(!fellowAppList.isEmpty()){
            fellowApplicationId = fellowAppList[0].Id;
        }

        return fellowApplicationId;

    }



}