force-app/main/default/objects/Contact/fields/Constituency__c.field-meta.xml
<CustomField>
    <fullName>Constituency__c</fullName>
    <label>Constituency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Constituency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Initial_Constituency__c.field-meta.xml
<CustomField>
    <fullName>Initial_Constituency__c</fullName>
    <inlineHelpText>Set automatically, capturing the initial Constituency value set for the Contact.  If multiple entered initially, 1st in alphabetical order is selected.</inlineHelpText>
    <label>Initial Constituency</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/classes/InitialConstituency_TDTM.cls
/**
 * Created by robertwright on 1/13/22.
 */

global without sharing class InitialConstituency_TDTM extends npsp.TDTM_RunnableMutable {
    global override void run(List<SObject> listNew, List<SObject> listOld,
            npsp.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult,
            npsp.TDTM_Runnable.DmlWrapper dmlWrapper) {
        if (objResult.SobjectType == Contact.SobjectType && triggerAction == npsp.TDTM_Runnable.Action.BeforeInsert) {
            for(Contact con : (list<Contact>) listNew) process(con);
        }
    }

    @TestVisible
    private static void  process(Contact con) {
        list<String> constituencies = new List<String>();
        if(string.isNotBlank(con.Constituency__c)) constituencies = con.Constituency__c.split(';');
        constituencies.sort();
        if(!constituencies.isEmpty()) con.Initial_Constituency__c = constituencies[0];
    }
}