force-app/main/default/objects/Contact/fields/Permanent_Street_Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Street_Address_Line_2__c</fullName>
    <label>Permanent Street Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Skype__c.field-meta.xml
<CustomField>
    <fullName>Skype__c</fullName>
    <label>Skype</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/CC_Year__c.field-meta.xml
<CustomField>
    <fullName>CC_Year__c</fullName>
    <label>CC Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Do_you_identify_as_Latinx_or_Hispanic__c.field-meta.xml
<CustomField>
    <fullName>Do_you_identify_as_Latinx_or_Hispanic__c</fullName>
    <label>Do you identify as Latinx or Hispanic?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Fellowship_Applying_for__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Applying_for__c</fullName>
    <label>Fellowship Applying for?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_Campus_Presentation__c.field-meta.xml
<CustomField>
    <fullName>How_Campus_Presentation__c</fullName>
    <label>How you learnt about Campus Presentation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Eventbrite Invitation</fullName>
            </value>
            <value>
                <fullName>Other online event site</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>Other social media site</fullName>
            </value>
            <value>
                <fullName>Student group announcement</fullName>
            </value>
            <value>
                <fullName>Campus career services announcement</fullName>
            </value>
            <value>
                <fullName>School program communication</fullName>
            </value>
            <value>
                <fullName>Bulletin board posting</fullName>
            </value>
            <value>
                <fullName>Former fellow communication</fullName>
            </value>
            <value>
                <fullName>Former host organization communication</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_did_find_out_about_EDF_Other__c.field-meta.xml
<CustomField>
    <fullName>How_did_find_out_about_EDF_Other__c</fullName>
    <label>If other, how did you find out about EDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/How_Did_You_Find_Us__c.field-meta.xml
<CustomField>
    <fullName>How_Did_You_Find_Us__c</fullName>
    <description>Could be Picklist</description>
    <label>How did you find out about EDFCC?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Campus Presentation with EDF staff</fullName>
            </value>
            <value>
                <fullName>EDF Staff webinar</fullName>
            </value>
            <value>
                <fullName>Career services job posting</fullName>
            </value>
            <value>
                <fullName>Career Services staff</fullName>
            </value>
            <value>
                <fullName>EDF website</fullName>
            </value>
            <value>
                <fullName>Student group newsletter</fullName>
            </value>
            <value>
                <fullName>Word of Mouth  from an Alumni Fellow</fullName>
            </value>
            <value>
                <fullName>Word of Mouth from another source</fullName>
            </value>
            <value>
                <fullName>Online Job postings (e.g, indeed.com, idealist.org, greenbiz.com)</fullName>
            </value>
            <value>
                <fullName>National Black MBA Conference</fullName>
            </value>
            <value>
                <fullName>Prospanica conference</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Pronouns__c.field-meta.xml
<CustomField>
    <fullName>Pronouns__c</fullName>
    <label>Pronouns</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>He/Him/His</fullName>
            </value>
            <value>
                <fullName>She/Her/Hers</fullName>
            </value>
            <value>
                <fullName>They/Them/Theirs</fullName>
            </value>
            <value>
                <fullName>Prefer to self-describe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Pronouns_Self_Describe__c.field-meta.xml
<CustomField>
    <fullName>Pronouns_Self_Describe__c</fullName>
    <label>Pronouns Self Describe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Indian or Alaska Native</fullName>
            </value>
            <value>
                <fullName>Asian</fullName>
            </value>
            <value>
                <fullName>Black/African American</fullName>
            </value>
            <value>
                <fullName>Pacific Islander</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Returner_Fellow__c.field-meta.xml
<CustomField>
    <fullName>Returner_Fellow__c</fullName>
    <inlineHelpText>Have you participated in the Climate Corps program in the past?</inlineHelpText>
    <label>Returner Fellow</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Sex__c.field-meta.xml
<CustomField>
    <fullName>Sex__c</fullName>
    <label>Sex</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Genderqueer</fullName>
            </value>
            <value>
                <fullName>Man</fullName>
            </value>
            <value>
                <fullName>Non-Binary</fullName>
            </value>
            <value>
                <fullName>Woman</fullName>
            </value>
            <value>
                <fullName>Prefer to self-describe</fullName>
            </value>
            <value>
                <fullName>Prefer not to disclose</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Sex_Self_Describe__c.field-meta.xml
<CustomField>
    <fullName>Sex_Self_Describe__c</fullName>
    <description>Provide a description for Gender if Prefer to Self-Describe is selected.</description>
    <label>Sex Self Describe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Skype__c.field-meta.xml
<CustomField>
    <fullName>Skype__c</fullName>
    <label>Skype</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Veteran_Status__c.field-meta.xml
<CustomField>
    <fullName>Veteran_Status__c</fullName>
    <inlineHelpText>Classification of Protected Veteran - 
Disabled veteran
Recently separated veteran
Active duty wartime or campaign badge veteran
Armed forces service medal veteran</inlineHelpText>
    <label>Veteran Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>I identify as one or more of the classifications of protected veteran</fullName>
            </value>
            <value>
                <fullName>I am not a protected veteran</fullName>
            </value>
            <value>
                <fullName>I decline to self-identify</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CustomMetadataHelper.cls
public with sharing class CustomMetadataHelper {



    @AuraEnabled( cacheable=true )
    public static List <PortalFellowAppField__mdt> fetchPortalPageFieldDetails(String sectionName) {

        List < PortalFellowAppField__mdt > fieldList
            = [SELECT Id,
                    MasterLabel, DeveloperName, Order__c, Row_Type__c,
                    Field_Type__c, Field_Label__c, Field_API_Name__c,
                    Object_API_Name__c, Is_Mandatory__c,
                    Picklist_Values__c, User_Defined_Picklist_Values__c,
                    Section__c, Editable__c,
                    Parent_Field__c, Show_On_Value__c
                FROM PortalFellowAppField__mdt
                WHERE Section__c = :sectionName
                ORDER BY Order__c ASC];

        System.debug('fetchPortalPageFieldDetails :: fieldList :: ' + fieldList);
        for (PortalFellowAppField__mdt field : fieldList) {
            if (field.Field_Type__c == 'Picklist'  ||  field.Field_Type__c == 'PicklistWithOther') {
                if (field.User_Defined_Picklist_Values__c == null) {
                    field.User_Defined_Picklist_Values__c = CustomMetadataHelper.getPicklistValues(field.Object_API_Name__c, field.Field_API_Name__c);
                }
            }
        }
        System.debug('fetchPortalPageFieldDetails :: fieldList :: ' + fieldList);
        return fieldList;
    }


    public static String getPicklistValues(String objAPIName, String fieldName) {

        // List<String> lstPickvals = new List<String>();
        String picklistValues = '';
        Schema.SObjectType targetType = Schema.getGlobalDescribe().get(objAPIName);//From the Object Api name retrieving the SObject
        Sobject Object_name = targetType.newSObject();
        Schema.sObjectType sobject_type = Object_name.getSObjectType(); //grab the sobject that was passed
        Schema.DescribeSObjectResult sobject_describe = sobject_type.getDescribe(); //describe the sobject
        Map<String, Schema.SObjectField> field_map = sobject_describe.fields.getMap(); //get a map of fields for the passed sobject
        List<Schema.PicklistEntry> pick_list_values = field_map.get(fieldName).getDescribe().getPickListValues(); //grab the list of picklist values for the passed field on the sobject
        for (Schema.PicklistEntry a : pick_list_values) { //for all values in the picklist list
            // lstPickvals.add(a.getValue());//add the value  to our final list
            picklistValues += a.getValue() + ' | ';
        }

        return picklistValues.left(picklistValues.length() - 2);
    }


    @AuraEnabled
    public static string updateFellowApplication(Fellow_Application__c fApp, Contact cont) {
        update fApp;
        update cont;
        return 'success';
    }

    public static String getContactId() {
        String contactId = '';
        String currUserId = Userinfo.getUserId();
        User[] users = [SELECT Id, FirstName, LastName, Contact.Name, username, ContactId, email
                        FROM User WHERE Id = :currUserId and ContactId <> null];
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            contactId = user.ContactId;
        }

        return contactId;
    }

    @AuraEnabled
    public static Contact getContactInfo() {
        String contactId = getContactId();
        Contact[] contList = [SELECT Id, Name,
                                FirstName,
                                LastName,
                                Email,
                                Phone,
                                MailingStreet,
                                Permanent_Street_Address_Line_2__c,
                                MailingCity,
                                MailingState,
                                MailingCountry,
                                MailingPostalCode FROM Contact WHERE Id = :contactId];
        return contList.get(0);
    }

    @AuraEnabled
    public static Fellow_Application__c getFellowAppInfo() {
        String contactId = getContactId();
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
		List<string> mailingStreets = new List<string>();
        Fellow_Application__c[] fellowApps = [SELECT Id,
                                Pronouns__c,
                                Pronouns_Self_Describe__c,
                                Fellowship_Applying_for__c,
                                Skype__c,
                                How_Did_You_Find_Us__c,
                                How_Campus_Presentation__c,
                                How_did_find_out_about_EDF_Other__c,
                                Returner_Fellow__c,
                                Sex__c,
                                Sex_Self_Describe__c,
                                Race__c,
                                Do_you_identify_as_Latinx_or_Hispanic__c,
                                Veteran_Status__c
                            FROM
                                Fellow_Application__c
                            WHERE
                                Applicant__c  =:contactId AND CC_Year__c=:fellowshipYear];

        return fellowApps.get(0);
    }

}