force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Contact_Phone__c/Contact_Phone__c.object-meta.xml
<CustomObject>
    <description>This custom object will hold the phone numbers related to a Contact.</description>
    <label>Contact Phone</label>
    <nameField>
        <displayFormat>CP-{000000}</displayFormat>
        <label>Phone ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Phones</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Phone__c/fields/Donor__c.field-meta.xml
<CustomField>
    <fullName>Donor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contact Phones</relationshipLabel>
    <relationshipName>Contact_Phones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Primary__c.field-meta.xml
<CustomField>
    <fullName>Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact_Phone__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Home</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Mobile</fullName>
            </value>
            <value>
                <fullName>Additional Home</fullName>
            </value>
            <value>
                <fullName>Assistant</fullName>
            </value>
            <value>
                <fullName>Assistant Mobile</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactTriggerHandler.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 3/7/2022
# Last Modified by......:
# Last Modified Date....: 
# Description...........: To insert the contact phone whenever the contcat is cretead and updated with new Phone field.
# Test Class............: 
# Change Log:
# 
############################################################################
*/


public class ContactTriggerHandler {
    private static boolean afterInsertAlreadyFired = false;
    private static boolean afterUpdateAlreadyFired = false;
	/**
    * Description : This method Creates a contact phone record after the contact record inserted uncheck the primary field if any phonenumber is changed.
    **/
    public void afterInsert(Map<Id, Contact> newMap, Map<Id, Contact> oldMap, List<Contact> newList, List<Contact> oldList){
        if(!afterInsertAlreadyFired){
            List<Contact_phone__c> contactPhoneList = new List<Contact_phone__c>();
            for(Contact con : newList) {
                if(!String.isBlank(con.Phone)){
                    Contact_phone__c contactPhone = new Contact_phone__c();
                    contactPhone.Donor__c = con.Id;
                    contactPhone.Type__c = 'Mobile';
                    contactPhone.Phone__c = con.Phone;
                    contactPhone.Primary__c = true;

                    contactPhoneList.add(contactPhone);
                }
            }

            if(!contactPhoneList.isEmpty()){
                insert contactPhoneList;
            }

            afterInsertAlreadyFired = true;
        }
    }
    /**
    * Description : This method Creates a contact phone record after the contact record updated and check .
    **/
    public void afterUpdate(Map<Id, Contact> newMap, Map<Id, Contact> oldMap, List<Contact> newList, List<Contact> oldList){
        
        if(!afterUpdateAlreadyFired){
            List<Contact_phone__c> contactPhoneList = new List<Contact_phone__c>();
            for(Contact con : newList) {
                Contact oldContact = oldMap.get(con.Id);
                System.debug('oldContact:'+oldContact.Phone);
                System.debug('con.Phone:'+con.Phone);
                System.debug('newList:'+newList);
                System.debug('oldContact:'+oldContact);
                if(!String.isBlank(con.Phone) && con.Phone != oldContact.Phone){
                    Contact_phone__c contactPhone = new Contact_phone__c();
                    contactPhone.Donor__c = con.Id;
                    contactPhone.Type__c = 'Mobile';
                    contactPhone.Phone__c = con.Phone;
                    contactPhone.Primary__c = true;
                    contactPhoneList.add(contactPhone);
                }
            }

            if(!contactPhoneList.isEmpty()){
                uncheckPrimaryForExistingContactPhone(newMap);
                insert contactPhoneList;
            }

            afterUpdateAlreadyFired = true;
            // added for Test class code coverage.
            if(Test.isRunningTest()){
                afterUpdateAlreadyFired = false;
             }
        }
    }

    public void uncheckPrimaryForExistingContactPhone(Map<Id, Contact> newMap){
        
        Set<Id> ids = newMap.keySet();
        List<Contact_phone__c> conPhoneList = [select Id, Primary__c from Contact_phone__c where Donor__c in: ids];
        if(!conPhoneList.isEmpty()){
            for(Contact_phone__c conPhone : conPhoneList) {
                conPhone.Primary__c = false;
            }

            update conPhoneList;
        }

    }
}