force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/CC_Year__c.field-meta.xml
<CustomField>
    <fullName>CC_Year__c</fullName>
    <label>CC Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RecordId__c/RecordId__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Record Ids</label>
</CustomObject>

force-app/main/default/objects/RecordId__c/fields/IdValue__c.field-meta.xml
<CustomField>
    <fullName>IdValue__c</fullName>
    <label>IdValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EdfContactController_Test.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 1/31/2022
# Last Modified by......:  
# Last Modified Date....: 
# Description...........: Test class for EdfContactController 
# Change Log:               
#
#
############################################################################
*/

@isTest
public class EdfContactController_Test {
    
    @testsetup
    public static void createTestData() {
        createCustomSettingData();
    }
    
    static testMethod void testCreateContact() {
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c; 
        Fellow_Application__c fa = new Fellow_Application__c(Applicant__c=c.Id,Status__c='Engagement Confirmed', CC_Year__c=fellowshipYear); insert fa;
        FellowAppWrapper fw = new FellowAppWrapper();
        fw.fellowApplicationId = String.valueOf(fa.id);
        fw.contactId = String.valueOf(c.id);
        fw.lastName = 'teja';
        Profile p = [SELECT Id FROM Profile WHERE Name='Fellow Portal Community User'];
        User u = new User(Alias = 'standt', Email='someone@abc.bix', 
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                          LocaleSidKey='en_US', ProfileId = p.Id, 
                          TimeZoneSidKey='America/Los_Angeles', UserName='someone@abc.bix.edf', FirstName='TestFN', ContactId=c.Id);
        insert u;
        System.runAs(u){
            EdfContactController.getContactForEDF();
            EdfContactController.getContact();
            EdfContactController.getfellowApplicationId(c.Id);
            EdfContactController.getContactInfo();
            EdfContactController.updateFellowApplication(fw);
        }
        
    }
    static testMethod void testUpdateContact() {
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='12389087', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c; 
        Contact c1 = new Contact(id=c.id,LastName='TestLNupdate');
        test.startTest();
        update c1;
        ContactWrapper cw = new ContactWrapper();
        cw.id=c.id;
        cw.lastName=c.LastName;
        EdfContactController.updateContact(cw);
        EdfContactController.getFellowshipApplyingForPickListValues();
        EdfContactController.getHowDidYouFindUsPickListValues();
        EdfContactController.getReturnerFellowPickListValues();
        EdfContactController.getGenderPickListValues();
        EdfContactController.getDoYouIdentifyAsLatinxOrHispanicPickListValues();
        EdfContactController.getVeteranStatusPickListValues();   
        test.StopTest();
        
    }
    
    public static void createCustomSettingData() {
        List<RecordId__c> recordIdCustomSetting = new List<RecordId__c>();
        if(RecordId__c.getAll().get('DefaultOwnerId') == NULL){
            recordIdCustomSetting.add(new RecordId__c(name = 'DefaultOwnerId',IdValue__c = string.valueOf(UserInfo.getUserId())));
        }
        if(recordIdCustomSetting.size()>0){
            insert recordIdCustomSetting;
        }        
    }
    
}