force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Fellowship_Applying_for__c.field-meta.xml
<CustomField>
    <fullName>Fellowship_Applying_for__c</fullName>
    <label>Fellowship Applying for?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>U.S. Fellowship</fullName>
            </value>
            <value>
                <fullName>China Fellowship</fullName>
            </value>
            <value>
                <fullName>India Fellowship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potential_Matching_From_Screener__c/Potential_Matching_From_Screener__c.object-meta.xml
<CustomObject>
    <description>This join object will hold the student’s application and the engagement information. The object will hold those engagements the student is asking to be considered for, after selecting the “Consider Me” button next to the engagement on the student portal. EDF staff will also use this object as a result of the matching process initiated by an EDF staff person from the student application or engagement record.</description>
    <label>Consider Me- Fellow Portal</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>PE Match #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consider Me- Fellow Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Potential_Matching_From_Screener__c/fields/How_Considered__c.field-meta.xml
<CustomField>
    <fullName>How_Considered__c</fullName>
    <label>How Considered</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Consider Me</fullName>
            </value>
            <value>
                <fullName>EDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potential_Matching_From_Screener__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Deleting the existing records when end user selects new set of records</description>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Potential_Matching_From_Screener__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Tracks various status of Consider Me from Fellow Portal</description>
    <inlineHelpText>Bookmarked = Bookmarked only with no comments
Ranked = Ranked only with no comments
Not Submitted = Added comments but not submitted
Submitted = Submitted
Archived = Original submission</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bookmarked</fullName>
            </value>
            <value>
                <fullName>Ranked</fullName>
            </value>
            <value>
                <fullName>Not Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Potential_Matching_From_Screener__c/fields/Student_Application__c.field-meta.xml
<CustomField>
    <fullName>Student_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student Application</label>
    <referenceTo>Fellow_Application__c</referenceTo>
    <relationshipName>Potential_Matching_From_Screeners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RecordId__c/RecordId__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Record Ids</label>
</CustomObject>

force-app/main/default/objects/RecordId__c/fields/IdValue__c.field-meta.xml
<CustomField>
    <fullName>IdValue__c</fullName>
    <label>IdValue</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EngagementListControllerTest.cls
@isTest
public class EngagementListControllerTest {
    @testsetup
    public static void createTestData() {
        createCustomSettingData();
    }
    public static void createCustomSettingData() {
        List<RecordId__c> recordIdCustomSetting = new List<RecordId__c>();
        if(RecordId__c.getAll().get('DefaultOwnerId') == NULL){
            recordIdCustomSetting.add(new RecordId__c(name = 'DefaultOwnerId',IdValue__c = string.valueOf(UserInfo.getUserId())));
        }
        if(recordIdCustomSetting.size()>0){
            insert recordIdCustomSetting;
        }
    }

    static testMethod void getFellowshipForTest(){

        EngagementListController elc = new EngagementListController();
        EngagementListController.getFellowshipFor();
    }
    static testMethod void getFelloWAppIdTest(){
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c;
        Fellow_Application__c fa = new Fellow_Application__c(Applicant__c=c.Id,Status__c='Engagement Confirmed',Fellowship_Applying_for__c='U.S. Fellowship'); insert fa;
        FellowAppWrapper fw = new FellowAppWrapper();
        Profile p = [SELECT Id FROM Profile WHERE Name='Fellow Portal Community User'];
        User u = new User(Alias = 'standt', Email='someone@abc.bix',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='someone@abc.bix.edf', FirstName='TestFN', ContactId=c.Id);
        insert u;
        System.runAs(u){
            EngagementListController.getFelloWAppId();
            EngagementListController.getFellowshipApplyingFor();
            EngagementListController.getEngagementListSettings('U.S. Fellowship');
        }


    }



    static testMethod void searchEngagementsTest(){
        EngagementListController.SearchFilterWrapper sfw =new EngagementListController.SearchFilterWrapper();
        sfw.fellowshipcity = 'test';
            sfw.fellowshipstate = 'test';
            sfw.publicTransport = 'test';
            sfw.industry = 'test';
            sfw.availableNotAvailable = 'test';
            sfw.projectType = 'test';
            sfw.locationPreferance = 'test';
            // sfw.engagementProgram = 'test'; // Commented by HSingh FB-2139
            sfw.searchText = 'test';
        EngagementListController.searchEngagements(sfw);
    }

    static testMethod void saveConsiderMeTest(){
        Account a = new Account(Name='Test Account', OwnerId=CustomSettings_Helper.getRecordIdsValue('DefaultOwnerId')); insert a;
        Contact c = new Contact(FirstName='TestFN', LastName='TestLN', Email='someone@abc.bix', Phone='9876543210', MailingStreet='Street', MailingCity='New Delhi', MailingState='Delhi', MailingCountry='India', MailingPostalCode='110060'); insert c;
        Fellow_Application__c fa = new Fellow_Application__c(Applicant__c=c.Id,Status__c='Engagement Confirmed',Fellowship_Applying_for__c='U.S. Fellowship'); insert fa;
        FellowAppWrapper fw = new FellowAppWrapper();
        Profile p = [SELECT Id FROM Profile WHERE Name='Fellow Portal Community User'];
        User u = new User(Alias = 'standt', Email='someone@abc.bix',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles', UserName='someone@abc.bix.edf', FirstName='TestFN', ContactId=c.Id);
        insert u;
        List<Potential_Matching_From_Screener__c> listPms =new List<Potential_Matching_From_Screener__c>();
        Potential_Matching_From_Screener__c pms=new Potential_Matching_From_Screener__c();
        pms.How_Considered__c = 'Consider Me';
        pms.Is_Deleted__c = false;
        pms.Student_Application__c =fa.Id;
        listPms.add(pms);
        System.runAs(u){
            EngagementListController.submitConsiderMe(listPms,fa.Id);
            EngagementListController.saveConsiderMe(listPms,fa.Id);
        }
    }

}