force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Fellow_Application__c/Fellow_Application__c.object-meta.xml
<CustomObject>
    <description>One-to-Many relationship with Contacts (applicants)</description>
    <label>Fellow Application</label>
    <nameField>
        <displayFormat>APP-{0000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fellow Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fellow_Application__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/CC_Year__c.field-meta.xml
<CustomField>
    <fullName>CC_Year__c</fullName>
    <label>CC Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2007</fullName>
            </value>
            <value>
                <fullName>2008</fullName>
            </value>
            <value>
                <fullName>2009</fullName>
            </value>
            <value>
                <fullName>2010</fullName>
            </value>
            <value>
                <fullName>2011</fullName>
            </value>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fellow_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospective Applicant</fullName>
            </value>
            <value>
                <fullName>Application Submitted</fullName>
            </value>
            <value>
                <fullName>Not Qualified and Notified</fullName>
            </value>
            <value>
                <fullName>Application Screened</fullName>
            </value>
            <value>
                <fullName>Interview 1 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 1 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Interview 2 Scheduled</fullName>
            </value>
            <value>
                <fullName>Interview 2 Complete- Not Moving On</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Accepted</fullName>
            </value>
            <value>
                <fullName>Conditional Offer Declined</fullName>
            </value>
            <value>
                <fullName>Onboarding Conversation Not Approved</fullName>
            </value>
            <value>
                <fullName>Engagement Confirmed</fullName>
            </value>
            <value>
                <fullName>Dropped out after confirmation and removed from network</fullName>
            </value>
            <value>
                <fullName>Declined from Matching Pool</fullName>
            </value>
            <value>
                <fullName>Offer Sent</fullName>
            </value>
            <value>
                <fullName>Host Dropped after Confirmation</fullName>
            </value>
            <value>
                <fullName>Waitlist- Interview 1</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 1</fullName>
            </value>
            <value>
                <fullName>Declined During Interview Process</fullName>
            </value>
            <value>
                <fullName>Invite to Interview from Waitlist</fullName>
            </value>
            <value>
                <fullName>Hold on Interview 2</fullName>
            </value>
            <value>
                <fullName>Not Moving Forward from Waitlist</fullName>
            </value>
            <value>
                <fullName>Send Invite for Interview 2</fullName>
                <label>Send invite for Interview 2</label>
            </value>
            <value>
                <fullName>Hold on Matching</fullName>
            </value>
            <value>
                <fullName>Send to Matching Pool</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FellowApplicationStatus__c/FellowApplicationStatus__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of Internal Fellow App Status matching external App status. Contains a mapping only if internal and external values differ.</description>
    <label>FellowApplicationStatus</label>
</CustomObject>

force-app/main/default/objects/FellowApplicationStatus__c/fields/StatusName__c.field-meta.xml
<CustomField>
    <fullName>StatusName__c</fullName>
    <label>StatusName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LoginController.cls
/*
###########################################################################
# Created by............: Suresh Tavva & Team (OSI)
# Created Date..........: 12/21/2021
# Last Modified by......:
# Last Modified Date....:
# Description...........: Login Functinality Controller.
# Test Class............: LoginController_Test
# Change Log:
#
############################################################################
*/
public without sharing class LoginController {

    @AuraEnabled
    public static boolean login(String strUsername,String strPassword){
        system.debug('strUsername'+strUsername);
        system.debug('strPassword'+strPassword);
        integer UserCount=[select count() from user where Username=:strUsername limit 1];
        if (UserCount>0){
            system.debug('in');
           // PageReference empRedirect = Site.login(strUsername, strPassword,'/loginRedirectPage');
            return true;
        }else{
            system.debug('out');
            return false;
        }

    }

    @AuraEnabled(cacheable=true)
    public static UserWrapper getUserDetails(){
        UserWrapper uw = new UserWrapper();
        string userName = '';
        String currUserId = Userinfo.getUserId();
        //String currUserId = '0051D000009L6tBQAS';
        User[] users = fetchCommunityUser(currUserId);
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            uw.id = user.Id;
            uw.userName = user.Firstname + ' ' + user.LastName;
        }

        //userName = currUserId;
        return uw;

    }

    @AuraEnabled(cacheable=true)
    public static String getUserName(){
        string userName = '';
        String currUserId = Userinfo.getUserId();
        User[] users = fetchCommunityUser(currUserId);
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            userName = 'Welcome, ' + user.Firstname + ' ' + user.LastName;
        }

        return userName;

    }

    @AuraEnabled(cacheable=true)
    public static String getApplicationStatusForLogin(){
        String applicationStatus = '';
        String currUserId = Userinfo.getUserId();
        User[] users = fetchCommunityUser(currUserId);
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            String contactId = user.ContactId;
			System.debug('contactId:'+contactId);
            List<Fellow_Application__c> fellowAppList = [SELECT Id,
                                    Applicant__c,
                                    Status__c
                                FROM
                                    Fellow_Application__c
                                WHERE
                                    Applicant__c  = :contactId AND CC_Year__c=:fellowshipYear LIMIT 1];
            System.debug('fellowAppList:'+fellowAppList);
            if(!fellowAppList.isEmpty()){
                //applicationStatus = getFellowApplicationStatusValue(fellowAppList[0].Status__c);
                applicationStatus = fellowAppList[0].Status__c;
            }
        }

        return applicationStatus;

    }

    @AuraEnabled(cacheable=true)
    public static String getApplicationStatus(){
        String applicationStatus = '';
        String currUserId = Userinfo.getUserId();
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        User[] users = fetchCommunityUser(currUserId);
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            String contactId = user.ContactId;
			System.debug('contactId:'+contactId);
            List<Fellow_Application__c> fellowAppList = [SELECT Id,
                                    Applicant__c,
                                    Status__c
                                FROM
                                    Fellow_Application__c
                                WHERE
                                    Applicant__c  = :contactId AND CC_Year__c=:fellowshipYear LIMIT 1];
            System.debug('fellowAppList:'+fellowAppList);
            if(!fellowAppList.isEmpty()){
                applicationStatus = 'Application Status: ' + getFellowApplicationStatusValue(fellowAppList[0].Status__c);
            }
        }

        return applicationStatus;

    }

    @AuraEnabled(cacheable=true)
    public static String getApplicationStatusValue(){
        String applicationStatus = '';
        String currUserId = Userinfo.getUserId();
        User[] users = fetchCommunityUser(currUserId);
        String fellowshipYear = EDF02_CustomMetadata_Helper.getEDFCCGlobalValue('CurrentFellowshipYear');
        if (users != null  &&  users.size() > 0){
            User user = users.get(0);
            String contactId = user.ContactId;
			System.debug('contactId:'+contactId);
            List<Fellow_Application__c> fellowAppList = [SELECT Id,
                                    Applicant__c,
                                    Status__c
                                FROM
                                    Fellow_Application__c
                                WHERE
                                    Applicant__c  = :contactId AND CC_Year__c=:fellowshipYear LIMIT 1];
            System.debug('fellowAppList:'+fellowAppList);
            if(!fellowAppList.isEmpty()){
                applicationStatus = getFellowApplicationStatusValue(fellowAppList[0].Status__c);
            }
        }

        return applicationStatus;

    }

    public static String getFellowApplicationStatusValue(String key) {
        String retVal = '';
        System.debug('Key:::::::' + key);
        if (key == null  ||  key == ''){
            key = '--';
            retVal = key;
        }

        // These two are hard-coded since there is 38 character limit on Custom Settings name
        // https://sites.secure.force.com/success/issues_view?id=a1p30000000Rq4hAAC
        if (key == 'Engagement Confirmed + Email Sent to OCS') {
            retVal = 'Engagement Confirmed';
        }
        else if (key == 'Declined after Interview 1 and before Interview 2') {
            retVal = 'Application Withdrawn';
        }
        else if (FellowApplicationStatus__c.getAll().get(key) != null) {
            retVal = FellowApplicationStatus__c.getAll().get(key).StatusName__c;
            if (retVal == null  ||  retVal == ''){
                retVal = key;
            }
        }
        System.debug('retVal:::::::' + retVal);
        return retVal;
    }

    public static User[] fetchCommunityUser(String currUserId) {
        return [SELECT Id, FirstName, LastName, Contact.Name, username, ContactId, email, Contact.Salutation
                        FROM User WHERE Id = :currUserId and ContactId <> null];
        // return [SELECT Id, FirstName, LastName, Contact.Name, username, ContactId, email
        //                 FROM User WHERE Id = :currUserId];
    }

    // @AuraEnabled
    // public static boolean forgotPasswordByEmail(String email) {
    //     System.debug('email:'+email);
    //     User[] users = [SELECT Id, name, firstName, lastName, alias, Username, email, Profile.Name, IsActive FROM User WHERE email = :email and Profile.Name = 'Fellow Portal Community User' LIMIT 1];
    //     System.debug('users:'+users);

    //     if(users!= null && users.size()>0){
    //         User user = users[0];
    //         system.debug('Username:' + user.Username);
    //         boolean reset = Site.forgotPassword(user.Username);
    //         system.debug('reset:' + reset);

    //         return reset;
    //     }

    //     return false;
    // }

    @AuraEnabled
    public static String forgotPasswordByEmail(String email) {
        String response = '';

        //response = email;
        System.debug('email:'+email);
        User[] users = [SELECT Id, name, firstName, lastName, alias, Username, email, Profile.Name, IsActive FROM User WHERE email = :email];
        System.debug('users:'+users);

        if(users!= null && users.size()>0){
            User user = users[0];
            system.debug('Username:' + user.Username);
            boolean reset = Site.forgotPassword(user.Username);
            system.debug('reset:' + reset);

            if(reset){
                response = 'success';
            }
        }

        return response;
    }

    public static String getUsernameByEmail(String email) {
        String username = '';
        System.debug('email:'+email);
        User[] users = [SELECT  Username, email, Profile.Name, IsActive FROM User WHERE email = :email and Profile.Name = 'Fellow Portal Community User' and IsActive = true];
        System.debug('users:'+users);

        if(users!= null && users.size()>0){
            User user = users[0];
            system.debug('Username:' + user.Username);
            username = user.Username;
        }

        return username;
    }

    // FB-2039
    @AuraEnabled(cacheable=true)
    public static Boolean isDeadlinePassed() {
        return FellowAppController.isDeadlinePassed();
    }
}